// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CreateMerchantRequestCategory.
const (
	Bakery     CreateMerchantRequestCategory = "bakery"
	Pharma     CreateMerchantRequestCategory = "pharma"
	Restaurant CreateMerchantRequestCategory = "restaurant"
)

// CreateActorRequest defines model for CreateActorRequest.
type CreateActorRequest struct {
	Email      openapi_types.Email `json:"email"`
	FullName   string              `json:"full_name"`
	MerchantId openapi_types.UUID  `json:"merchant_id"`
	Password   string              `json:"password"`
}

// CreateActorResponse defines model for CreateActorResponse.
type CreateActorResponse struct {
	Email      *openapi_types.Email `json:"email,omitempty"`
	FullName   *string              `json:"full_name,omitempty"`
	MerchantId *openapi_types.UUID  `json:"merchant_id,omitempty"`
	Uid        *openapi_types.UUID  `json:"uid,omitempty"`
}

// CreateMerchantRequest defines model for CreateMerchantRequest.
type CreateMerchantRequest struct {
	Address       string                        `json:"address"`
	Category      CreateMerchantRequestCategory `json:"category"`
	ContactNumber string                        `json:"contact_number"`
	Name          string                        `json:"name"`
	Ntn           string                        `json:"ntn"`
}

// CreateMerchantRequestCategory defines model for CreateMerchantRequest.Category.
type CreateMerchantRequestCategory string

// CreateMerchantResponse defines model for CreateMerchantResponse.
type CreateMerchantResponse struct {
	Address       *string             `json:"address,omitempty"`
	Category      *string             `json:"category,omitempty"`
	ContactNumber *string             `json:"contact_number,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	Name          *string             `json:"name,omitempty"`
	Ntn           *string             `json:"ntn,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code   *string `json:"code,omitempty"`
	Errors *string `json:"errors,omitempty"`
}

// LoginActorRequest defines model for LoginActorRequest.
type LoginActorRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginActorResponse defines model for LoginActorResponse.
type LoginActorResponse struct {
	AccessToken           *string              `json:"access_token,omitempty"`
	AccessTokenExpiresAt  *time.Time           `json:"access_token_expires_at,omitempty"`
	Email                 *openapi_types.Email `json:"email,omitempty"`
	RefreshToken          *string              `json:"refresh_token,omitempty"`
	RefreshTokenExpiresAt *time.Time           `json:"refresh_token_expires_at,omitempty"`
}

// RenewAccessTokenRequest defines model for RenewAccessTokenRequest.
type RenewAccessTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RenewAccessTokenResponse defines model for RenewAccessTokenResponse.
type RenewAccessTokenResponse struct {
	AccessToken          *string    `json:"access_token,omitempty"`
	AccessTokenExpiresAt *time.Time `json:"access_token_expires_at,omitempty"`
}

// PostApiV1ActorsJSONRequestBody defines body for PostApiV1Actors for application/json ContentType.
type PostApiV1ActorsJSONRequestBody = CreateActorRequest

// PostApiV1LoginJSONRequestBody defines body for PostApiV1Login for application/json ContentType.
type PostApiV1LoginJSONRequestBody = LoginActorRequest

// PostApiV1MerchantsJSONRequestBody defines body for PostApiV1Merchants for application/json ContentType.
type PostApiV1MerchantsJSONRequestBody = CreateMerchantRequest

// PostApiV1RenewTokenJSONRequestBody defines body for PostApiV1RenewToken for application/json ContentType.
type PostApiV1RenewTokenJSONRequestBody = RenewAccessTokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GET /api/v1/actor/{uid}
	// (GET /api/v1/actor/{uid})
	GetApiV1ActorUid(w http.ResponseWriter, r *http.Request, uid string)
	// POST /api/v1/actors
	// (POST /api/v1/actors)
	PostApiV1Actors(w http.ResponseWriter, r *http.Request)
	// POST /api/v1/login
	// (POST /api/v1/login)
	PostApiV1Login(w http.ResponseWriter, r *http.Request)
	// POST /api/v1/merchants
	// (POST /api/v1/merchants)
	PostApiV1Merchants(w http.ResponseWriter, r *http.Request)
	// POST /api/v1/renew-token
	// (POST /api/v1/renew-token)
	PostApiV1RenewToken(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GET /api/v1/actor/{uid}
// (GET /api/v1/actor/{uid})
func (_ Unimplemented) GetApiV1ActorUid(w http.ResponseWriter, r *http.Request, uid string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// POST /api/v1/actors
// (POST /api/v1/actors)
func (_ Unimplemented) PostApiV1Actors(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// POST /api/v1/login
// (POST /api/v1/login)
func (_ Unimplemented) PostApiV1Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// POST /api/v1/merchants
// (POST /api/v1/merchants)
func (_ Unimplemented) PostApiV1Merchants(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// POST /api/v1/renew-token
// (POST /api/v1/renew-token)
func (_ Unimplemented) PostApiV1RenewToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiV1ActorUid operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1ActorUid(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uid" -------------
	var uid string

	err = runtime.BindStyledParameterWithOptions("simple", "uid", chi.URLParam(r, "uid"), &uid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1ActorUid(w, r, uid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1Actors operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Actors(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1Actors(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1Login operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1Merchants operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Merchants(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1Merchants(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1RenewToken operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1RenewToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1RenewToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/actor/{uid}", wrapper.GetApiV1ActorUid)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/actors", wrapper.PostApiV1Actors)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/login", wrapper.PostApiV1Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/merchants", wrapper.PostApiV1Merchants)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/renew-token", wrapper.PostApiV1RenewToken)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RX34/bNgz+Vwxtj744Wd/ylhu6otuKHtrb+nAIAsVmYrW2pFJUuyDw/z5QziX22e65",
	"RXM/3hyFJj9+H0nRe5Ga0hoNmpyY74VLcyhlePwdQRIsUjL4Dj57cMSnFo0FJAXBBkqpCn7YGCwlifnh",
	"JBa0syDmwhEqvRVVLDa+KFZalsDmnX9LwDSXmlYqa7nzXmV93qx07qvBrMdZFQuEz14hZGJ+0/LcRBEf",
	"oR59LY+BzPojpMSBWiw4a7SDJ0SDH2VXDeb15hBvUGCZZQjO9YJNJcHW4C4woH3JbCM4kh6lJiY2l1hK",
	"EYu1/AS4a/DbcGI0yZRW2pdrwN44g2xp0vfrfxCbbeNjOg3wHQjLEWwNFcJYun6EhpEl8f1sdbJ9ifit",
	"ak9N1h8B+D03MsjfZqv0T5su4+fBqK5vghvUOk3BuRWZT6B76WgarOA/qxDcSlIroUwSXJAKJdrlc3z+",
	"CBsEl38DTcviB+D0afgONHxdhDSv2e2gkvfBu6NR23w5KvJjydTlpYqFg9Sjot17vk5rHJcgEXDhKedf",
	"6/Drj1v/f364FnF9+bKn+t9TrJzIioodK70x/H4GLkVlSRkt5mLhyVxsQQNKgizaoCkjhK1yBAhZlOYq",
	"QuMJePCRooJ9vjLRB1hHi6vX0aVRBaAtJHF+XwBd7XY2mU6mTJGxoKVVYi5eTKaTF6F7KA9pJdKq5Mss",
	"kdwsyd6rrOLjLQQCWQjJIF9nHBJoYdW/s9BY/4TxZSXKEgh4bNzsheKw7FvcDjJRj7lTdRB6OFAl+ypp",
	"ycZ1MQSAv02n9dDSBDqAktYWKg2wko/O6NPew0+/ImzEXPySnBaj5LAVJX3LQJClLcfbv0Q420hf0E8L",
	"3p7KPWGDQav8AqfNwrtZMj/Ol6Xki0i8enkd9SnITlrngUprXI+qV8Y1ZHUHscDRpcl256G+njJVe2xw",
	"YVQd8WcPLX5tlj12BRwlvnr7/o7GriVvwVfdCHXDlXgmcbu7wChtp2cB8JT7ul/VWsKmqLffEWPa9s3R",
	"9pyde/dL41Gat7PAP7f+PenaVBt5Gbo4bjj36B1Wp7A0nUnwoa3wgXt6cEV8Rp3dVLaqqur/AAAA//+V",
	"5HOSrxEAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
