// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email    openapi_types.Email `json:"email"`
	FullName string              `json:"full_name"`
	Password string              `json:"password"`
}

// CreateUserResponse defines model for CreateUserResponse.
type CreateUserResponse struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	FullName *string              `json:"full_name,omitempty"`
	Uid      *openapi_types.UUID  `json:"uid,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code   *string `json:"code,omitempty"`
	Errors *string `json:"errors,omitempty"`
}

// LoginUserRequest defines model for LoginUserRequest.
type LoginUserRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginUserResponse defines model for LoginUserResponse.
type LoginUserResponse struct {
	AccessToken           *string              `json:"access_token,omitempty"`
	AccessTokenExpiresAt  *time.Time           `json:"access_token_expires_at,omitempty"`
	Email                 *openapi_types.Email `json:"email,omitempty"`
	RefreshToken          *string              `json:"refresh_token,omitempty"`
	RefreshTokenExpiresAt *time.Time           `json:"refresh_token_expires_at,omitempty"`
}

// RenewAccessTokenRequest defines model for RenewAccessTokenRequest.
type RenewAccessTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RenewAccessTokenResponse defines model for RenewAccessTokenResponse.
type RenewAccessTokenResponse struct {
	AccessToken          *string    `json:"access_token,omitempty"`
	AccessTokenExpiresAt *time.Time `json:"access_token_expires_at,omitempty"`
}

// PostApiV1LoginJSONRequestBody defines body for PostApiV1Login for application/json ContentType.
type PostApiV1LoginJSONRequestBody = LoginUserRequest

// PostApiV1RenewTokenJSONRequestBody defines body for PostApiV1RenewToken for application/json ContentType.
type PostApiV1RenewTokenJSONRequestBody = RenewAccessTokenRequest

// PostApiV1UsersJSONRequestBody defines body for PostApiV1Users for application/json ContentType.
type PostApiV1UsersJSONRequestBody = CreateUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// POST /api/v1/login
	// (POST /api/v1/login)
	PostApiV1Login(w http.ResponseWriter, r *http.Request)
	// POST /api/v1/renew-token
	// (POST /api/v1/renew-token)
	PostApiV1RenewToken(w http.ResponseWriter, r *http.Request)
	// GET /api/v1/user/{uid}
	// (GET /api/v1/user/{uid})
	GetApiV1UserUid(w http.ResponseWriter, r *http.Request, uid string)
	// POST /api/v1/users
	// (POST /api/v1/users)
	PostApiV1Users(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// POST /api/v1/login
// (POST /api/v1/login)
func (_ Unimplemented) PostApiV1Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// POST /api/v1/renew-token
// (POST /api/v1/renew-token)
func (_ Unimplemented) PostApiV1RenewToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GET /api/v1/user/{uid}
// (GET /api/v1/user/{uid})
func (_ Unimplemented) GetApiV1UserUid(w http.ResponseWriter, r *http.Request, uid string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// POST /api/v1/users
// (POST /api/v1/users)
func (_ Unimplemented) PostApiV1Users(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostApiV1Login operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1RenewToken operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1RenewToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1RenewToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1UserUid operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1UserUid(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uid" -------------
	var uid string

	err = runtime.BindStyledParameterWithOptions("simple", "uid", chi.URLParam(r, "uid"), &uid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1UserUid(w, r, uid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1Users operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Users(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1Users(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/login", wrapper.PostApiV1Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/renew-token", wrapper.PostApiV1RenewToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/user/{uid}", wrapper.GetApiV1UserUid)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/users", wrapper.PostApiV1Users)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9SWX0/jOBDAv0rku8fQtMdb3sqJQ9yuBOLP8oCqyiTT1mxim/EEtqry3VdjlzahKVQr",
	"yrJviT2ef7+ZsRciM6U1GjQ5kS6Ey2ZQSv/5L4IkuHaAF/BQgSNetGgsICnwIlBKVfDHxGApSaTLlVjQ",
	"3IJIhSNUeirqWEyqohhrWQKLb+xa6dyTwbxjs44FwkOlEHKR3jb0xCtjq9OjlWFzdw8ZsepmGM4a7WCP",
	"cVQqb6mpeCHuCGnDzWNE84qHmcm7LQKfc9152zDy1UyVfi+iuzPbiVPDt21JkFkGzo3JfAfdmYymwBh+",
	"WIXgxpJa8eSS4ICUL6DNbO4ePsIEwc1e8aYl8QvudBG8AA1PQx/mFavdCvIt914gaouPdrL8uzBt5qWO",
	"hYOsQkXzSx5gwY8jkAg4rGjGf3f+779n/f/fXIk4jDvWFHbXtmZEVtSsWOmJ4fM5uAyVJWW0SMWwInMw",
	"BQ0oCfJogqaMEKbKESDkUTZTEZqKwLFKRQXrPDHRDdxFw/PT6MioAtAWkji+R0AX1A56/V6fU2QsaGmV",
	"SMVhr9879M1DMx9WIq1KHgdJwQ3js29CATADyf6d5iIV58bR0KpvA99YIuAGR0cmn4eJogm0PyitLVTm",
	"jyb3zuj1RcBffyNMRCr+StY3RbK8JpKNgVK3C4uwAr8QasX7/0+/vw/7y2r0DrRZnX0Rfm0iq4LezXR7",
	"YHeY9QKhNquylDhnKGeXV1EbIAs8ryD32MGqcd4A6zvS9+Ke6G4bNh8Meevk+YNYN8k2iVcOMFlUKq/Z",
	"hyl08D6BgJvL/No/J6xEWQIB3/u3C8FTwI8HEYvwMhHh2dFGFDeCfTlRR3vE1/EA+5TglheIT2nz6rgd",
	"cXrWXE+O11gb+F5SdTt08LWX20/zbj7fd2rbwQdzD1L55+zawLGu6/pnAAAA//9lagejKA0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
