// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: actor.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createActor = `-- name: CreateActor :one
INSERT INTO actors (
    merchant_id,
    email,
    password_hash,
    first_name,
    last_name,
    is_active,
    last_login
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING
    id AS uid,
    email,
    trim(concat(first_name, ' ', last_name)) AS full_name,
    created_at,
    modified_at
`

type CreateActorParams struct {
	MerchantID   uuid.UUID
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	IsActive     bool
	LastLogin    time.Time
}

type CreateActorRow struct {
	UID        uuid.UUID
	Email      string
	FullName   string
	CreatedAt  time.Time
	ModifiedAt time.Time
}

func (q *Queries) CreateActor(ctx context.Context, arg CreateActorParams) (CreateActorRow, error) {
	row := q.db.QueryRow(ctx, createActor,
		arg.MerchantID,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.IsActive,
		arg.LastLogin,
	)
	var i CreateActorRow
	err := row.Scan(
		&i.UID,
		&i.Email,
		&i.FullName,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getActor = `-- name: GetActor :one
SELECT
    a.merchant_id,
    a.id AS uid,
    a.email,
    a.password_hash AS password,
    trim(concat(a.first_name, ' ', a.last_name)) AS full_name,
    a.is_active,
    a.last_login,
    a.created_at,
    a.modified_at
FROM actors a
WHERE a.merchant_id = $1
  AND a.email = $2
LIMIT 1
`

type GetActorParams struct {
	MerchantID uuid.UUID
	Email      string
}

type GetActorRow struct {
	MerchantID uuid.UUID
	UID        uuid.UUID
	Email      string
	Password   string
	FullName   string
	IsActive   bool
	LastLogin  time.Time
	CreatedAt  time.Time
	ModifiedAt time.Time
}

func (q *Queries) GetActor(ctx context.Context, arg GetActorParams) (GetActorRow, error) {
	row := q.db.QueryRow(ctx, getActor, arg.MerchantID, arg.Email)
	var i GetActorRow
	err := row.Scan(
		&i.MerchantID,
		&i.UID,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getActorByUID = `-- name: GetActorByUID :one
SELECT
    a.merchant_id,
    a.id AS uid,
    a.email,
    a.password_hash AS password,
    trim(concat(a.first_name, ' ', a.last_name)) AS full_name,
    a.is_active,
    a.last_login,
    a.created_at,
    a.modified_at
FROM actors a
WHERE a.merchant_id = $1
  AND a.id = $2
LIMIT 1
`

type GetActorByUIDParams struct {
	MerchantID uuid.UUID
	ID         uuid.UUID
}

type GetActorByUIDRow struct {
	MerchantID uuid.UUID
	UID        uuid.UUID
	Email      string
	Password   string
	FullName   string
	IsActive   bool
	LastLogin  time.Time
	CreatedAt  time.Time
	ModifiedAt time.Time
}

func (q *Queries) GetActorByUID(ctx context.Context, arg GetActorByUIDParams) (GetActorByUIDRow, error) {
	row := q.db.QueryRow(ctx, getActorByUID, arg.MerchantID, arg.ID)
	var i GetActorByUIDRow
	err := row.Scan(
		&i.MerchantID,
		&i.UID,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const updateActor = `-- name: UpdateActor :one
UPDATE actors
SET
        first_name = $3,
        last_name = $4,
        is_active = $5,
        last_login = $6,
        modified_at = NOW()
WHERE merchant_id = $1
    AND id = $2
RETURNING
        merchant_id,
        id AS uid,
        email,
        password_hash AS password,
        trim(concat(first_name, ' ', last_name)) AS full_name,
        is_active,
        last_login,
        created_at,
        modified_at
`

type UpdateActorParams struct {
	MerchantID uuid.UUID
	ID         uuid.UUID
	FirstName  string
	LastName   string
	IsActive   bool
	LastLogin  time.Time
}

type UpdateActorRow struct {
	MerchantID uuid.UUID
	UID        uuid.UUID
	Email      string
	Password   string
	FullName   string
	IsActive   bool
	LastLogin  time.Time
	CreatedAt  time.Time
	ModifiedAt time.Time
}

func (q *Queries) UpdateActor(ctx context.Context, arg UpdateActorParams) (UpdateActorRow, error) {
	row := q.db.QueryRow(ctx, updateActor,
		arg.MerchantID,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.IsActive,
		arg.LastLogin,
	)
	var i UpdateActorRow
	err := row.Scan(
		&i.MerchantID,
		&i.UID,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
