// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: actor_role.sql

package pgsqlc

import (
	"context"

	"github.com/google/uuid"
)

const assignActorRole = `-- name: AssignActorRole :one
INSERT INTO actor_roles (
    merchant_id,
    actor_id,
    role_id
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (merchant_id, actor_id)
DO UPDATE SET
    role_id = EXCLUDED.role_id,
    assigned_at = NOW()
RETURNING merchant_id, actor_id, role_id, assigned_at
`

type AssignActorRoleParams struct {
	MerchantID uuid.UUID
	ActorID    uuid.UUID
	RoleID     uuid.UUID
}

func (q *Queries) AssignActorRole(ctx context.Context, arg AssignActorRoleParams) (ActorRole, error) {
	row := q.db.QueryRow(ctx, assignActorRole, arg.MerchantID, arg.ActorID, arg.RoleID)
	var i ActorRole
	err := row.Scan(
		&i.MerchantID,
		&i.ActorID,
		&i.RoleID,
		&i.AssignedAt,
	)
	return i, err
}

const getActorRole = `-- name: GetActorRole :one
SELECT
    merchant_id,
    actor_id,
    role_id,
    assigned_at
FROM actor_roles
WHERE merchant_id = $1 AND actor_id = $2
LIMIT 1
`

type GetActorRoleParams struct {
	MerchantID uuid.UUID
	ActorID    uuid.UUID
}

func (q *Queries) GetActorRole(ctx context.Context, arg GetActorRoleParams) (ActorRole, error) {
	row := q.db.QueryRow(ctx, getActorRole, arg.MerchantID, arg.ActorID)
	var i ActorRole
	err := row.Scan(
		&i.MerchantID,
		&i.ActorID,
		&i.RoleID,
		&i.AssignedAt,
	)
	return i, err
}

const touchActorRoleAssignedAt = `-- name: TouchActorRoleAssignedAt :one
UPDATE actor_roles
SET
    assigned_at = NOW()
WHERE merchant_id = $1 AND actor_id = $2
RETURNING merchant_id, actor_id, role_id, assigned_at
`

type TouchActorRoleAssignedAtParams struct {
	MerchantID uuid.UUID
	ActorID    uuid.UUID
}

func (q *Queries) TouchActorRoleAssignedAt(ctx context.Context, arg TouchActorRoleAssignedAtParams) (ActorRole, error) {
	row := q.db.QueryRow(ctx, touchActorRoleAssignedAt, arg.MerchantID, arg.ActorID)
	var i ActorRole
	err := row.Scan(
		&i.MerchantID,
		&i.ActorID,
		&i.RoleID,
		&i.AssignedAt,
	)
	return i, err
}
