// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: branch.sql

package pgsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (
    merchant_id,
    name,
    address,
    contact_number,
    city
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, merchant_id, name, address, contact_number, city, created_at, updated_at
`

type CreateBranchParams struct {
	MerchantID    uuid.UUID
	Name          string
	Address       string
	ContactNumber pgtype.Text
	City          CityType
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.MerchantID,
		arg.Name,
		arg.Address,
		arg.ContactNumber,
		arg.City,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Address,
		&i.ContactNumber,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBranch = `-- name: GetBranch :one
SELECT
    id,
    merchant_id,
    name,
    address,
    contact_number,
    city,
    created_at,
    updated_at
FROM branches
WHERE merchant_id = $1 AND id = $2
LIMIT 1
`

type GetBranchParams struct {
	MerchantID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) GetBranch(ctx context.Context, arg GetBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranch, arg.MerchantID, arg.ID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Address,
		&i.ContactNumber,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branches
SET
    name = $3,
    address = $4,
    contact_number = $5,
    city = $6,
    updated_at = NOW()
WHERE merchant_id = $1 AND id = $2
RETURNING id, merchant_id, name, address, contact_number, city, created_at, updated_at
`

type UpdateBranchParams struct {
	MerchantID    uuid.UUID
	ID            uuid.UUID
	Name          string
	Address       string
	ContactNumber pgtype.Text
	City          CityType
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.MerchantID,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.ContactNumber,
		arg.City,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Address,
		&i.ContactNumber,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
