// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: cart_item.sql

package pgsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCartItem = `-- name: GetCartItem :one
SELECT
    cart_id,
    product_id,
    quantity,
    addon_ids,
    applied_discount_id,
    applied_discount_amount
FROM cart_items
WHERE cart_id = $1 AND product_id = $2
LIMIT 1
`

type GetCartItemParams struct {
	CartID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) GetCartItem(ctx context.Context, arg GetCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItem, arg.CartID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.AddonIds,
		&i.AppliedDiscountID,
		&i.AppliedDiscountAmount,
	)
	return i, err
}

const updateCartItem = `-- name: UpdateCartItem :one
UPDATE cart_items
SET
    quantity = $3,
    addon_ids = $4,
    applied_discount_id = $5,
    applied_discount_amount = $6
WHERE cart_id = $1 AND product_id = $2
RETURNING cart_id, product_id, quantity, addon_ids, applied_discount_id, applied_discount_amount
`

type UpdateCartItemParams struct {
	CartID                uuid.UUID
	ProductID             uuid.UUID
	Quantity              int32
	AddonIds              []uuid.UUID
	AppliedDiscountID     uuid.UUID
	AppliedDiscountAmount pgtype.Numeric
}

func (q *Queries) UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItem,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.AddonIds,
		arg.AppliedDiscountID,
		arg.AppliedDiscountAmount,
	)
	var i CartItem
	err := row.Scan(
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.AddonIds,
		&i.AppliedDiscountID,
		&i.AppliedDiscountAmount,
	)
	return i, err
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO cart_items (
    cart_id,
    product_id,
    quantity,
    addon_ids,
    applied_discount_id,
    applied_discount_amount
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (cart_id, product_id)
DO UPDATE
SET
    quantity = EXCLUDED.quantity,
    addon_ids = EXCLUDED.addon_ids,
    applied_discount_id = EXCLUDED.applied_discount_id,
    applied_discount_amount = EXCLUDED.applied_discount_amount
RETURNING cart_id, product_id, quantity, addon_ids, applied_discount_id, applied_discount_amount
`

type UpsertCartItemParams struct {
	CartID                uuid.UUID
	ProductID             uuid.UUID
	Quantity              int32
	AddonIds              []uuid.UUID
	AppliedDiscountID     uuid.UUID
	AppliedDiscountAmount pgtype.Numeric
}

func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItem,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.AddonIds,
		arg.AppliedDiscountID,
		arg.AppliedDiscountAmount,
	)
	var i CartItem
	err := row.Scan(
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.AddonIds,
		&i.AppliedDiscountID,
		&i.AppliedDiscountAmount,
	)
	return i, err
}
