// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: catalog_read.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getProductDetail = `-- name: GetProductDetail :one
SELECT
    p.id,
    p.merchant_id,
    p.category_id,
    p.name,
    p.description,
    p.base_price,
    p.image_url,
    p.track_inventory,
    p.is_active,
    p.created_at,
    p.updated_at,
    COALESCE(pc.name, '') AS category_name
FROM products p
LEFT JOIN product_categories pc
  ON pc.merchant_id = p.merchant_id
 AND pc.id = p.category_id
WHERE p.merchant_id = $1
  AND p.id = $2
LIMIT 1
`

type GetProductDetailParams struct {
	MerchantID uuid.UUID
	ID         uuid.UUID
}

type GetProductDetailRow struct {
	ID             uuid.UUID
	MerchantID     uuid.UUID
	CategoryID     uuid.UUID
	Name           string
	Description    pgtype.Text
	BasePrice      pgtype.Numeric
	ImageUrl       pgtype.Text
	TrackInventory bool
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CategoryName   string
}

func (q *Queries) GetProductDetail(ctx context.Context, arg GetProductDetailParams) (GetProductDetailRow, error) {
	row := q.db.QueryRow(ctx, getProductDetail, arg.MerchantID, arg.ID)
	var i GetProductDetailRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.BasePrice,
		&i.ImageUrl,
		&i.TrackInventory,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
	)
	return i, err
}

const listInventoryByMerchant = `-- name: ListInventoryByMerchant :many
SELECT
    p.id AS product_id,
    p.name AS product_name,
    COALESCE(SUM(pi.quantity), 0)::int AS quantity
FROM products p
LEFT JOIN product_inventory pi
  ON pi.product_id = p.id
WHERE p.merchant_id = $1
GROUP BY p.id, p.name
ORDER BY p.name
`

type ListInventoryByMerchantRow struct {
	ProductID   uuid.UUID
	ProductName string
	Quantity    int32
}

func (q *Queries) ListInventoryByMerchant(ctx context.Context, merchantID uuid.UUID) ([]ListInventoryByMerchantRow, error) {
	rows, err := q.db.Query(ctx, listInventoryByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryByMerchantRow{}
	for rows.Next() {
		var i ListInventoryByMerchantRow
		if err := rows.Scan(&i.ProductID, &i.ProductName, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductAddonsByProduct = `-- name: ListProductAddonsByProduct :many
SELECT
    pa.id,
    pa.product_id,
    pa.name,
    pa.price,
    pa.created_at
FROM product_addons pa
WHERE pa.product_id = $1
ORDER BY pa.created_at DESC, pa.id
`

func (q *Queries) ListProductAddonsByProduct(ctx context.Context, productID uuid.UUID) ([]ProductAddon, error) {
	rows, err := q.db.Query(ctx, listProductAddonsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductAddon{}
	for rows.Next() {
		var i ProductAddon
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductCategoriesByMerchant = `-- name: ListProductCategoriesByMerchant :many
SELECT
    id,
    merchant_id,
    name,
    description,
    created_at
FROM product_categories
WHERE merchant_id = $1
ORDER BY created_at DESC, id
`

func (q *Queries) ListProductCategoriesByMerchant(ctx context.Context, merchantID uuid.UUID) ([]ProductCategory, error) {
	rows, err := q.db.Query(ctx, listProductCategoriesByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductCategory{}
	for rows.Next() {
		var i ProductCategory
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByMerchant = `-- name: ListProductsByMerchant :many
SELECT
    id,
    merchant_id,
    category_id,
    name,
    description,
    base_price,
    image_url,
    track_inventory,
    is_active,
    created_at,
    updated_at
FROM products
WHERE merchant_id = $1
ORDER BY created_at DESC, id
`

func (q *Queries) ListProductsByMerchant(ctx context.Context, merchantID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.BasePrice,
			&i.ImageUrl,
			&i.TrackInventory,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
