// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: coverage_read.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listAreas = `-- name: ListAreas :many
SELECT
    id,
    name,
    city,
    created_at
FROM areas
ORDER BY city, name, id
`

func (q *Queries) ListAreas(ctx context.Context) ([]Area, error) {
	rows, err := q.db.Query(ctx, listAreas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Area{}
	for rows.Next() {
		var i Area
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantServiceZonesByMerchant = `-- name: ListMerchantServiceZonesByMerchant :many
SELECT
    msz.id,
    msz.merchant_id,
    msz.zone_id,
    msz.branch_id,
    msz.created_at,
    z.name AS zone_name,
    ST_AsText(z.coordinates) AS zone_coordinates_wkt,
    a.id AS area_id,
    a.name AS area_name,
    a.city AS area_city,
    COALESCE(b.name, '') AS branch_name
FROM merchant_service_zones msz
JOIN zones z
  ON z.id = msz.zone_id
JOIN areas a
  ON a.id = z.area_id
LEFT JOIN branches b
  ON b.id = msz.branch_id
WHERE msz.merchant_id = $1
ORDER BY msz.created_at DESC, msz.id
`

type ListMerchantServiceZonesByMerchantRow struct {
	ID                 uuid.UUID
	MerchantID         uuid.UUID
	ZoneID             uuid.UUID
	BranchID           uuid.UUID
	CreatedAt          time.Time
	ZoneName           string
	ZoneCoordinatesWkt interface{}
	AreaID             uuid.UUID
	AreaName           string
	AreaCity           CityType
	BranchName         string
}

func (q *Queries) ListMerchantServiceZonesByMerchant(ctx context.Context, merchantID uuid.UUID) ([]ListMerchantServiceZonesByMerchantRow, error) {
	rows, err := q.db.Query(ctx, listMerchantServiceZonesByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantServiceZonesByMerchantRow{}
	for rows.Next() {
		var i ListMerchantServiceZonesByMerchantRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.ZoneID,
			&i.BranchID,
			&i.CreatedAt,
			&i.ZoneName,
			&i.ZoneCoordinatesWkt,
			&i.AreaID,
			&i.AreaName,
			&i.AreaCity,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZonesByArea = `-- name: ListZonesByArea :many
SELECT
    id,
    area_id,
    name,
    ST_AsText(coordinates) AS coordinates_wkt,
    created_at
FROM zones
WHERE area_id = $1
ORDER BY name, id
`

type ListZonesByAreaRow struct {
	ID             uuid.UUID
	AreaID         uuid.UUID
	Name           string
	CoordinatesWkt interface{}
	CreatedAt      time.Time
}

func (q *Queries) ListZonesByArea(ctx context.Context, areaID uuid.UUID) ([]ListZonesByAreaRow, error) {
	rows, err := q.db.Query(ctx, listZonesByArea, areaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZonesByAreaRow{}
	for rows.Next() {
		var i ListZonesByAreaRow
		if err := rows.Scan(
			&i.ID,
			&i.AreaID,
			&i.Name,
			&i.CoordinatesWkt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
