// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: merchant_service_zone.sql

package pgsqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMerchantServiceZone = `-- name: CreateMerchantServiceZone :one
INSERT INTO merchant_service_zones (
    merchant_id,
    zone_id,
    branch_id
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, merchant_id, zone_id, branch_id, created_at
`

type CreateMerchantServiceZoneParams struct {
	MerchantID uuid.UUID
	ZoneID     uuid.UUID
	BranchID   uuid.UUID
}

func (q *Queries) CreateMerchantServiceZone(ctx context.Context, arg CreateMerchantServiceZoneParams) (MerchantServiceZone, error) {
	row := q.db.QueryRow(ctx, createMerchantServiceZone, arg.MerchantID, arg.ZoneID, arg.BranchID)
	var i MerchantServiceZone
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ZoneID,
		&i.BranchID,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantServiceZone = `-- name: GetMerchantServiceZone :one
SELECT
    id,
    merchant_id,
    zone_id,
    branch_id,
    created_at
FROM merchant_service_zones
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetMerchantServiceZone(ctx context.Context, id uuid.UUID) (MerchantServiceZone, error) {
	row := q.db.QueryRow(ctx, getMerchantServiceZone, id)
	var i MerchantServiceZone
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ZoneID,
		&i.BranchID,
		&i.CreatedAt,
	)
	return i, err
}

const updateMerchantServiceZone = `-- name: UpdateMerchantServiceZone :one
UPDATE merchant_service_zones
SET
    branch_id = $2
WHERE id = $1
RETURNING id, merchant_id, zone_id, branch_id, created_at
`

type UpdateMerchantServiceZoneParams struct {
	ID       uuid.UUID
	BranchID uuid.UUID
}

func (q *Queries) UpdateMerchantServiceZone(ctx context.Context, arg UpdateMerchantServiceZoneParams) (MerchantServiceZone, error) {
	row := q.db.QueryRow(ctx, updateMerchantServiceZone, arg.ID, arg.BranchID)
	var i MerchantServiceZone
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ZoneID,
		&i.BranchID,
		&i.CreatedAt,
	)
	return i, err
}
