// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: merchant_discount.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMerchantDiscount = `-- name: CreateMerchantDiscount :one
INSERT INTO merchant_discounts (
    merchant_id,
    type,
    value,
    description,
    valid_from,
    valid_to
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, merchant_id, type, value, description, valid_from, valid_to, created_at
`

type CreateMerchantDiscountParams struct {
	MerchantID  uuid.UUID
	Type        DiscountType
	Value       pgtype.Numeric
	Description pgtype.Text
	ValidFrom   time.Time
	ValidTo     time.Time
}

func (q *Queries) CreateMerchantDiscount(ctx context.Context, arg CreateMerchantDiscountParams) (MerchantDiscount, error) {
	row := q.db.QueryRow(ctx, createMerchantDiscount,
		arg.MerchantID,
		arg.Type,
		arg.Value,
		arg.Description,
		arg.ValidFrom,
		arg.ValidTo,
	)
	var i MerchantDiscount
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Type,
		&i.Value,
		&i.Description,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantDiscount = `-- name: GetMerchantDiscount :one
SELECT
    id,
    merchant_id,
    type,
    value,
    description,
    valid_from,
    valid_to,
    created_at
FROM merchant_discounts
WHERE merchant_id = $1 AND id = $2
LIMIT 1
`

type GetMerchantDiscountParams struct {
	MerchantID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) GetMerchantDiscount(ctx context.Context, arg GetMerchantDiscountParams) (MerchantDiscount, error) {
	row := q.db.QueryRow(ctx, getMerchantDiscount, arg.MerchantID, arg.ID)
	var i MerchantDiscount
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Type,
		&i.Value,
		&i.Description,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
	)
	return i, err
}

const updateMerchantDiscount = `-- name: UpdateMerchantDiscount :one
UPDATE merchant_discounts
SET
    type = $3,
    value = $4,
    description = $5,
    valid_from = $6,
    valid_to = $7
WHERE merchant_id = $1 AND id = $2
RETURNING id, merchant_id, type, value, description, valid_from, valid_to, created_at
`

type UpdateMerchantDiscountParams struct {
	MerchantID  uuid.UUID
	ID          uuid.UUID
	Type        DiscountType
	Value       pgtype.Numeric
	Description pgtype.Text
	ValidFrom   time.Time
	ValidTo     time.Time
}

func (q *Queries) UpdateMerchantDiscount(ctx context.Context, arg UpdateMerchantDiscountParams) (MerchantDiscount, error) {
	row := q.db.QueryRow(ctx, updateMerchantDiscount,
		arg.MerchantID,
		arg.ID,
		arg.Type,
		arg.Value,
		arg.Description,
		arg.ValidFrom,
		arg.ValidTo,
	)
	var i MerchantDiscount
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Type,
		&i.Value,
		&i.Description,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
	)
	return i, err
}
