// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: order_item.sql

package pgsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOrderItem = `-- name: GetOrderItem :one
SELECT
    order_id,
    product_id,
    quantity,
    price,
    base_amount,
    addon_amount,
    discount_amount,
    tax_amount,
    line_total
FROM order_items
WHERE order_id = $1 AND product_id = $2
LIMIT 1
`

type GetOrderItemParams struct {
	OrderID   uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) GetOrderItem(ctx context.Context, arg GetOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItem, arg.OrderID, arg.ProductID)
	var i OrderItem
	err := row.Scan(
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.BaseAmount,
		&i.AddonAmount,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.LineTotal,
	)
	return i, err
}

const updateOrderItem = `-- name: UpdateOrderItem :one
UPDATE order_items
SET
    quantity = $3,
    price = $4,
    base_amount = $5,
    addon_amount = $6,
    discount_amount = $7,
    tax_amount = $8,
    line_total = $9
WHERE order_id = $1 AND product_id = $2
RETURNING order_id, product_id, quantity, price, base_amount, addon_amount, discount_amount, tax_amount, line_total
`

type UpdateOrderItemParams struct {
	OrderID        uuid.UUID
	ProductID      uuid.UUID
	Quantity       int32
	Price          pgtype.Numeric
	BaseAmount     pgtype.Numeric
	AddonAmount    pgtype.Numeric
	DiscountAmount pgtype.Numeric
	TaxAmount      pgtype.Numeric
	LineTotal      pgtype.Numeric
}

func (q *Queries) UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, updateOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
		arg.BaseAmount,
		arg.AddonAmount,
		arg.DiscountAmount,
		arg.TaxAmount,
		arg.LineTotal,
	)
	var i OrderItem
	err := row.Scan(
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.BaseAmount,
		&i.AddonAmount,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.LineTotal,
	)
	return i, err
}

const upsertOrderItem = `-- name: UpsertOrderItem :one
INSERT INTO order_items (
    order_id,
    product_id,
    quantity,
    price,
    base_amount,
    addon_amount,
    discount_amount,
    tax_amount,
    line_total
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (order_id, product_id)
DO UPDATE
SET
    quantity = EXCLUDED.quantity,
    price = EXCLUDED.price,
    base_amount = EXCLUDED.base_amount,
    addon_amount = EXCLUDED.addon_amount,
    discount_amount = EXCLUDED.discount_amount,
    tax_amount = EXCLUDED.tax_amount,
    line_total = EXCLUDED.line_total
RETURNING order_id, product_id, quantity, price, base_amount, addon_amount, discount_amount, tax_amount, line_total
`

type UpsertOrderItemParams struct {
	OrderID        uuid.UUID
	ProductID      uuid.UUID
	Quantity       int32
	Price          pgtype.Numeric
	BaseAmount     pgtype.Numeric
	AddonAmount    pgtype.Numeric
	DiscountAmount pgtype.Numeric
	TaxAmount      pgtype.Numeric
	LineTotal      pgtype.Numeric
}

func (q *Queries) UpsertOrderItem(ctx context.Context, arg UpsertOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, upsertOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
		arg.BaseAmount,
		arg.AddonAmount,
		arg.DiscountAmount,
		arg.TaxAmount,
		arg.LineTotal,
	)
	var i OrderItem
	err := row.Scan(
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.BaseAmount,
		&i.AddonAmount,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.LineTotal,
	)
	return i, err
}
