// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: order_read.sql

package pgsqlc

import (
	"context"

	"github.com/google/uuid"
)

const listOrderItemAddonsByOrder = `-- name: ListOrderItemAddonsByOrder :many
SELECT
    order_id,
    product_id,
    addon_id,
    addon_name,
    addon_price,
    quantity,
    line_addon_total
FROM order_item_addons
WHERE order_id = $1
ORDER BY product_id, addon_id
`

func (q *Queries) ListOrderItemAddonsByOrder(ctx context.Context, orderID uuid.UUID) ([]OrderItemAddon, error) {
	rows, err := q.db.Query(ctx, listOrderItemAddonsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItemAddon{}
	for rows.Next() {
		var i OrderItemAddon
		if err := rows.Scan(
			&i.OrderID,
			&i.ProductID,
			&i.AddonID,
			&i.AddonName,
			&i.AddonPrice,
			&i.Quantity,
			&i.LineAddonTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrder = `-- name: ListOrderItemsByOrder :many
SELECT
    order_id,
    product_id,
    quantity,
    price,
    base_amount,
    addon_amount,
    discount_amount,
    tax_amount,
    line_total
FROM order_items
WHERE order_id = $1
ORDER BY product_id
`

func (q *Queries) ListOrderItemsByOrder(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.BaseAmount,
			&i.AddonAmount,
			&i.DiscountAmount,
			&i.TaxAmount,
			&i.LineTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByMerchant = `-- name: ListOrdersByMerchant :many
SELECT
    id,
    cart_id,
    merchant_id,
    branch_id,
    actor_id,
    payment_type,
    vat_rate,
    total_amount,
    status,
    delivery_address,
    customer_name,
    customer_phone,
    created_at,
    updated_at
FROM orders
WHERE merchant_id = $1
ORDER BY created_at DESC, id
`

func (q *Queries) ListOrdersByMerchant(ctx context.Context, merchantID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.MerchantID,
			&i.BranchID,
			&i.ActorID,
			&i.PaymentType,
			&i.VatRate,
			&i.TotalAmount,
			&i.Status,
			&i.DeliveryAddress,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
