// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: order_item_addon.sql

package pgsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOrderItemAddon = `-- name: GetOrderItemAddon :one
SELECT
    order_id,
    product_id,
    addon_id,
    addon_name,
    addon_price,
    quantity,
    line_addon_total
FROM order_item_addons
WHERE order_id = $1 AND product_id = $2 AND addon_id = $3
LIMIT 1
`

type GetOrderItemAddonParams struct {
	OrderID   uuid.UUID
	ProductID uuid.UUID
	AddonID   uuid.UUID
}

func (q *Queries) GetOrderItemAddon(ctx context.Context, arg GetOrderItemAddonParams) (OrderItemAddon, error) {
	row := q.db.QueryRow(ctx, getOrderItemAddon, arg.OrderID, arg.ProductID, arg.AddonID)
	var i OrderItemAddon
	err := row.Scan(
		&i.OrderID,
		&i.ProductID,
		&i.AddonID,
		&i.AddonName,
		&i.AddonPrice,
		&i.Quantity,
		&i.LineAddonTotal,
	)
	return i, err
}

const updateOrderItemAddon = `-- name: UpdateOrderItemAddon :one
UPDATE order_item_addons
SET
    addon_name = $4,
    addon_price = $5,
    quantity = $6,
    line_addon_total = $7
WHERE order_id = $1 AND product_id = $2 AND addon_id = $3
RETURNING order_id, product_id, addon_id, addon_name, addon_price, quantity, line_addon_total
`

type UpdateOrderItemAddonParams struct {
	OrderID        uuid.UUID
	ProductID      uuid.UUID
	AddonID        uuid.UUID
	AddonName      string
	AddonPrice     pgtype.Numeric
	Quantity       int32
	LineAddonTotal pgtype.Numeric
}

func (q *Queries) UpdateOrderItemAddon(ctx context.Context, arg UpdateOrderItemAddonParams) (OrderItemAddon, error) {
	row := q.db.QueryRow(ctx, updateOrderItemAddon,
		arg.OrderID,
		arg.ProductID,
		arg.AddonID,
		arg.AddonName,
		arg.AddonPrice,
		arg.Quantity,
		arg.LineAddonTotal,
	)
	var i OrderItemAddon
	err := row.Scan(
		&i.OrderID,
		&i.ProductID,
		&i.AddonID,
		&i.AddonName,
		&i.AddonPrice,
		&i.Quantity,
		&i.LineAddonTotal,
	)
	return i, err
}

const upsertOrderItemAddon = `-- name: UpsertOrderItemAddon :one
INSERT INTO order_item_addons (
    order_id,
    product_id,
    addon_id,
    addon_name,
    addon_price,
    quantity,
    line_addon_total
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (order_id, product_id, addon_id)
DO UPDATE
SET
    addon_name = EXCLUDED.addon_name,
    addon_price = EXCLUDED.addon_price,
    quantity = EXCLUDED.quantity,
    line_addon_total = EXCLUDED.line_addon_total
RETURNING order_id, product_id, addon_id, addon_name, addon_price, quantity, line_addon_total
`

type UpsertOrderItemAddonParams struct {
	OrderID        uuid.UUID
	ProductID      uuid.UUID
	AddonID        uuid.UUID
	AddonName      string
	AddonPrice     pgtype.Numeric
	Quantity       int32
	LineAddonTotal pgtype.Numeric
}

func (q *Queries) UpsertOrderItemAddon(ctx context.Context, arg UpsertOrderItemAddonParams) (OrderItemAddon, error) {
	row := q.db.QueryRow(ctx, upsertOrderItemAddon,
		arg.OrderID,
		arg.ProductID,
		arg.AddonID,
		arg.AddonName,
		arg.AddonPrice,
		arg.Quantity,
		arg.LineAddonTotal,
	)
	var i OrderItemAddon
	err := row.Scan(
		&i.OrderID,
		&i.ProductID,
		&i.AddonID,
		&i.AddonName,
		&i.AddonPrice,
		&i.Quantity,
		&i.LineAddonTotal,
	)
	return i, err
}
