// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: product_inventory.sql

package pgsqlc

import (
	"context"

	"github.com/google/uuid"
)

const getProductInventory = `-- name: GetProductInventory :one
SELECT
    id,
    product_id,
    branch_id,
    quantity,
    created_at,
    updated_at
FROM product_inventory
WHERE product_id = $1 AND branch_id = $2
LIMIT 1
`

type GetProductInventoryParams struct {
	ProductID uuid.UUID
	BranchID  uuid.UUID
}

func (q *Queries) GetProductInventory(ctx context.Context, arg GetProductInventoryParams) (ProductInventory, error) {
	row := q.db.QueryRow(ctx, getProductInventory, arg.ProductID, arg.BranchID)
	var i ProductInventory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductInventoryQuantity = `-- name: UpdateProductInventoryQuantity :one
UPDATE product_inventory
SET
    quantity = $3,
    updated_at = NOW()
WHERE product_id = $1 AND branch_id = $2
RETURNING id, product_id, branch_id, quantity, created_at, updated_at
`

type UpdateProductInventoryQuantityParams struct {
	ProductID uuid.UUID
	BranchID  uuid.UUID
	Quantity  int32
}

func (q *Queries) UpdateProductInventoryQuantity(ctx context.Context, arg UpdateProductInventoryQuantityParams) (ProductInventory, error) {
	row := q.db.QueryRow(ctx, updateProductInventoryQuantity, arg.ProductID, arg.BranchID, arg.Quantity)
	var i ProductInventory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProductInventory = `-- name: UpsertProductInventory :one
INSERT INTO product_inventory (
    product_id,
    branch_id,
    quantity
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (product_id, branch_id)
DO UPDATE
SET
    quantity = EXCLUDED.quantity,
    updated_at = NOW()
RETURNING id, product_id, branch_id, quantity, created_at, updated_at
`

type UpsertProductInventoryParams struct {
	ProductID uuid.UUID
	BranchID  uuid.UUID
	Quantity  int32
}

func (q *Queries) UpsertProductInventory(ctx context.Context, arg UpsertProductInventoryParams) (ProductInventory, error) {
	row := q.db.QueryRow(ctx, upsertProductInventory, arg.ProductID, arg.BranchID, arg.Quantity)
	var i ProductInventory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
