// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: reporting.sql

package pgsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMonthlySalesReport = `-- name: GetMonthlySalesReport :one
SELECT
    COALESCE(SUM(oi.line_total), 0)::numeric AS total_sales,
    COALESCE(SUM(oi.tax_amount), 0)::numeric AS total_tax,
    COALESCE(SUM(oi.discount_amount), 0)::numeric AS total_discount,
    COALESCE(SUM(oi.base_amount + oi.addon_amount - oi.discount_amount), 0)::numeric AS profit_estimate
FROM orders o
JOIN order_items oi
  ON oi.order_id = o.id
WHERE o.merchant_id = $1
  AND o.status IN ('accepted', 'out_for_delivery', 'delivered')
  AND EXTRACT(MONTH FROM o.created_at)::int = $2::int
  AND EXTRACT(YEAR FROM o.created_at)::int = $3::int
`

type GetMonthlySalesReportParams struct {
	MerchantID uuid.UUID
	Month      int32
	Year       int32
}

type GetMonthlySalesReportRow struct {
	TotalSales     pgtype.Numeric
	TotalTax       pgtype.Numeric
	TotalDiscount  pgtype.Numeric
	ProfitEstimate pgtype.Numeric
}

func (q *Queries) GetMonthlySalesReport(ctx context.Context, arg GetMonthlySalesReportParams) (GetMonthlySalesReportRow, error) {
	row := q.db.QueryRow(ctx, getMonthlySalesReport, arg.MerchantID, arg.Month, arg.Year)
	var i GetMonthlySalesReportRow
	err := row.Scan(
		&i.TotalSales,
		&i.TotalTax,
		&i.TotalDiscount,
		&i.ProfitEstimate,
	)
	return i, err
}
