// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: session.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGuestSession = `-- name: CreateGuestSession :one
INSERT INTO sessions (
	id,
	merchant_id,
	actor_id,
	refresh_token,
	user_agent,
	client_ip,
	is_blocked,
	expires_at
)
VALUES (
	$1,
	$2,
	NULL,
	$3,
	$4,
	$5,
	$6,
	$7
)
RETURNING id, merchant_id, actor_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at
`

type CreateGuestSessionParams struct {
	ID           uuid.UUID
	MerchantID   uuid.UUID
	RefreshToken string
	UserAgent    string
	ClientIP     string
	IsBlocked    bool
	ExpiresAt    time.Time
}

func (q *Queries) CreateGuestSession(ctx context.Context, arg CreateGuestSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createGuestSession,
		arg.ID,
		arg.MerchantID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIP,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ActorID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIP,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
WITH inserted AS (
	INSERT INTO sessions (
		id,
		merchant_id,
		actor_id,
		refresh_token,
		user_agent,
		client_ip,
		is_blocked,
		expires_at
	)
	VALUES (
		$1,
		$2,
		$3,
		$4,
		$5,
		$6,
		$7,
		$8
	)
	RETURNING id, merchant_id, actor_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at
)
SELECT
	inserted.id AS id,
	inserted.id AS uid,
	a.email AS actor_email,
	inserted.refresh_token,
	inserted.user_agent,
	inserted.client_ip,
	inserted.is_blocked,
	inserted.expires_at,
	inserted.created_at
FROM inserted
JOIN actors a
  ON a.merchant_id = inserted.merchant_id
 AND a.id = inserted.actor_id
`

type CreateSessionParams struct {
	ID           uuid.UUID
	MerchantID   uuid.UUID
	ActorID      pgtype.UUID
	RefreshToken string
	UserAgent    string
	ClientIP     string
	IsBlocked    bool
	ExpiresAt    time.Time
}

type CreateSessionRow struct {
	ID           uuid.UUID
	UID          uuid.UUID
	ActorEmail   string
	RefreshToken string
	UserAgent    string
	ClientIP     string
	IsBlocked    bool
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.MerchantID,
		arg.ActorID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIP,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UID,
		&i.ActorEmail,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIP,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT
	s.id AS id,
	s.id AS uid,
	COALESCE(a.email, '') AS actor_email,
	s.refresh_token,
	s.user_agent,
	s.client_ip,
	s.is_blocked,
	s.expires_at,
	s.created_at
FROM sessions s
LEFT JOIN actors a ON a.merchant_id = s.merchant_id AND a.id = s.actor_id
WHERE s.id = $1 LIMIT 1
`

type GetSessionRow struct {
	ID           uuid.UUID
	UID          uuid.UUID
	ActorEmail   string
	RefreshToken string
	UserAgent    string
	ClientIP     string
	IsBlocked    bool
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UID,
		&i.ActorEmail,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIP,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionBlockStatus = `-- name: UpdateSessionBlockStatus :one
UPDATE sessions
SET
	is_blocked = $2
WHERE id = $1
RETURNING id, merchant_id, actor_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at
`

type UpdateSessionBlockStatusParams struct {
	ID        uuid.UUID
	IsBlocked bool
}

func (q *Queries) UpdateSessionBlockStatus(ctx context.Context, arg UpdateSessionBlockStatusParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionBlockStatus, arg.ID, arg.IsBlocked)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ActorID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIP,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionRefresh = `-- name: UpdateSessionRefresh :one
UPDATE sessions
SET
	refresh_token = $2,
	user_agent = $3,
	client_ip = $4,
	expires_at = $5
WHERE id = $1
RETURNING id, merchant_id, actor_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at
`

type UpdateSessionRefreshParams struct {
	ID           uuid.UUID
	RefreshToken string
	UserAgent    string
	ClientIP     string
	ExpiresAt    time.Time
}

func (q *Queries) UpdateSessionRefresh(ctx context.Context, arg UpdateSessionRefreshParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionRefresh,
		arg.ID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIP,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ActorID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIP,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
