// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: vat_rule.sql

package pgsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getVatRule = `-- name: GetVatRule :one
SELECT
    id,
    merchant_id,
    payment_type,
    rate,
    created_at
FROM vat_rules
WHERE merchant_id = $1 AND payment_type = $2
LIMIT 1
`

type GetVatRuleParams struct {
	MerchantID  uuid.UUID
	PaymentType PaymentType
}

func (q *Queries) GetVatRule(ctx context.Context, arg GetVatRuleParams) (VatRule, error) {
	row := q.db.QueryRow(ctx, getVatRule, arg.MerchantID, arg.PaymentType)
	var i VatRule
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PaymentType,
		&i.Rate,
		&i.CreatedAt,
	)
	return i, err
}

const updateVatRuleByID = `-- name: UpdateVatRuleByID :one
UPDATE vat_rules
SET
    payment_type = $3,
    rate = $4
WHERE merchant_id = $1 AND id = $2
RETURNING id, merchant_id, payment_type, rate, created_at
`

type UpdateVatRuleByIDParams struct {
	MerchantID  uuid.UUID
	ID          uuid.UUID
	PaymentType PaymentType
	Rate        pgtype.Numeric
}

func (q *Queries) UpdateVatRuleByID(ctx context.Context, arg UpdateVatRuleByIDParams) (VatRule, error) {
	row := q.db.QueryRow(ctx, updateVatRuleByID,
		arg.MerchantID,
		arg.ID,
		arg.PaymentType,
		arg.Rate,
	)
	var i VatRule
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PaymentType,
		&i.Rate,
		&i.CreatedAt,
	)
	return i, err
}

const upsertVatRule = `-- name: UpsertVatRule :one
INSERT INTO vat_rules (
    merchant_id,
    payment_type,
    rate
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (merchant_id, payment_type)
DO UPDATE
SET rate = EXCLUDED.rate
RETURNING id, merchant_id, payment_type, rate, created_at
`

type UpsertVatRuleParams struct {
	MerchantID  uuid.UUID
	PaymentType PaymentType
	Rate        pgtype.Numeric
}

func (q *Queries) UpsertVatRule(ctx context.Context, arg UpsertVatRuleParams) (VatRule, error) {
	row := q.db.QueryRow(ctx, upsertVatRule, arg.MerchantID, arg.PaymentType, arg.Rate)
	var i VatRule
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PaymentType,
		&i.Rate,
		&i.CreatedAt,
	)
	return i, err
}
