// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for BootstrapActorRequestRole.
const (
	BootstrapActorRequestRoleCustomer BootstrapActorRequestRole = "customer"
	BootstrapActorRequestRoleEmployee BootstrapActorRequestRole = "employee"
	BootstrapActorRequestRoleMerchant BootstrapActorRequestRole = "merchant"
)

// Defines values for CreateActorRequestRole.
const (
	CreateActorRequestRoleCustomer CreateActorRequestRole = "customer"
	CreateActorRequestRoleEmployee CreateActorRequestRole = "employee"
	CreateActorRequestRoleMerchant CreateActorRequestRole = "merchant"
)

// Defines values for CreateAreaRequestCity.
const (
	CreateAreaRequestCityKarachi CreateAreaRequestCity = "Karachi"
	CreateAreaRequestCityLahore  CreateAreaRequestCity = "Lahore"
)

// Defines values for CreateBranchRequestCity.
const (
	CreateBranchRequestCityKarachi CreateBranchRequestCity = "Karachi"
	CreateBranchRequestCityLahore  CreateBranchRequestCity = "Lahore"
)

// Defines values for CreateDiscountRequestType.
const (
	Flat       CreateDiscountRequestType = "flat"
	Percentage CreateDiscountRequestType = "percentage"
)

// Defines values for CreateMerchantRequestCategory.
const (
	CreateMerchantRequestCategoryBakery     CreateMerchantRequestCategory = "bakery"
	CreateMerchantRequestCategoryPharma     CreateMerchantRequestCategory = "pharma"
	CreateMerchantRequestCategoryRestaurant CreateMerchantRequestCategory = "restaurant"
)

// Defines values for CreateOrderRequestPaymentType.
const (
	CreateOrderRequestPaymentTypeCard CreateOrderRequestPaymentType = "card"
	CreateOrderRequestPaymentTypeCash CreateOrderRequestPaymentType = "cash"
)

// Defines values for UpdateMerchantRequestCategory.
const (
	UpdateMerchantRequestCategoryBakery     UpdateMerchantRequestCategory = "bakery"
	UpdateMerchantRequestCategoryPharma     UpdateMerchantRequestCategory = "pharma"
	UpdateMerchantRequestCategoryRestaurant UpdateMerchantRequestCategory = "restaurant"
)

// Defines values for UpdateOrderStatusRequestStatus.
const (
	Accepted       UpdateOrderStatusRequestStatus = "accepted"
	Cancelled      UpdateOrderStatusRequestStatus = "cancelled"
	Delivered      UpdateOrderStatusRequestStatus = "delivered"
	OutForDelivery UpdateOrderStatusRequestStatus = "out_for_delivery"
	Pending        UpdateOrderStatusRequestStatus = "pending"
	Refunded       UpdateOrderStatusRequestStatus = "refunded"
)

// Defines values for GetCartDetailParamsPaymentMethod.
const (
	GetCartDetailParamsPaymentMethodCard GetCartDetailParamsPaymentMethod = "card"
	GetCartDetailParamsPaymentMethodCash GetCartDetailParamsPaymentMethod = "cash"
)

// ActorProfileResponse defines model for ActorProfileResponse.
type ActorProfileResponse struct {
	Email      *openapi_types.Email `json:"email,omitempty"`
	FullName   *string              `json:"full_name,omitempty"`
	IsActive   *bool                `json:"is_active,omitempty"`
	LastLogin  *time.Time           `json:"last_login,omitempty"`
	MerchantId *openapi_types.UUID  `json:"merchant_id,omitempty"`
	Uid        *openapi_types.UUID  `json:"uid,omitempty"`
}

// AddCartItemRequest defines model for AddCartItemRequest.
type AddCartItemRequest struct {
	AddonIds   *[]openapi_types.UUID `json:"addon_ids,omitempty"`
	DiscountId *openapi_types.UUID   `json:"discount_id,omitempty"`
	ProductId  openapi_types.UUID    `json:"product_id"`
	Quantity   int                   `json:"quantity"`
}

// AreaResponse defines model for AreaResponse.
type AreaResponse struct {
	City      *string             `json:"city,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Name      *string             `json:"name,omitempty"`
}

// BootstrapActorRequest defines model for BootstrapActorRequest.
type BootstrapActorRequest struct {
	Email    openapi_types.Email       `json:"email"`
	FullName string                    `json:"full_name"`
	Password string                    `json:"password"`
	Role     BootstrapActorRequestRole `json:"role"`
}

// BootstrapActorRequestRole defines model for BootstrapActorRequest.Role.
type BootstrapActorRequestRole string

// BranchAvailabilityResponse defines model for BranchAvailabilityResponse.
type BranchAvailabilityResponse struct {
	BranchId    *openapi_types.UUID `json:"branch_id,omitempty"`
	BranchName  *string             `json:"branch_name,omitempty"`
	ClosingTime *string             `json:"closing_time,omitempty"`
	CurrentTime *string             `json:"current_time,omitempty"`
	IsOpen      *bool               `json:"is_open,omitempty"`
	MerchantId  *openapi_types.UUID `json:"merchant_id,omitempty"`
	OpeningTime *string             `json:"opening_time,omitempty"`
	Timezone    *string             `json:"timezone,omitempty"`
}

// BranchResponse defines model for BranchResponse.
type BranchResponse struct {
	Address       *string             `json:"address,omitempty"`
	City          *string             `json:"city,omitempty"`
	ClosingTime   *string             `json:"closing_time,omitempty"`
	ContactNumber *string             `json:"contact_number,omitempty"`
	CreatedAt     *time.Time          `json:"created_at,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	IsOpen        *bool               `json:"is_open,omitempty"`
	MerchantId    *openapi_types.UUID `json:"merchant_id,omitempty"`
	Name          *string             `json:"name,omitempty"`
	OpeningTime   *string             `json:"opening_time,omitempty"`
	UpdatedAt     *time.Time          `json:"updated_at,omitempty"`
}

// CartDetailResponse defines model for CartDetailResponse.
type CartDetailResponse struct {
	CartId        *openapi_types.UUID    `json:"cart_id,omitempty"`
	Discount      *CartDiscountResponse  `json:"discount,omitempty"`
	PaymentMethod *string                `json:"payment_method,omitempty"`
	Products      *[]CartProductResponse `json:"products,omitempty"`
	Subtotal      *float64               `json:"subtotal,omitempty"`
	TotalPrice    *float64               `json:"total_price,omitempty"`
	TotalVat      *float64               `json:"total_vat,omitempty"`
	VatRate       *float64               `json:"vat_rate,omitempty"`
}

// CartDiscountResponse defines model for CartDiscountResponse.
type CartDiscountResponse struct {
	Amount      *float64            `json:"amount,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Type        *string             `json:"type,omitempty"`
	Value       *float64            `json:"value,omitempty"`
}

// CartItemResponse defines model for CartItemResponse.
type CartItemResponse struct {
	ItemId    *openapi_types.UUID `json:"item_id,omitempty"`
	ProductId *openapi_types.UUID `json:"product_id,omitempty"`
	Quantity  *int                `json:"quantity,omitempty"`
}

// CartProductAddonResponse defines model for CartProductAddonResponse.
type CartProductAddonResponse struct {
	Id    *openapi_types.UUID `json:"id,omitempty"`
	Name  *string             `json:"name,omitempty"`
	Price *float64            `json:"price,omitempty"`
}

// CartProductResponse defines model for CartProductResponse.
type CartProductResponse struct {
	Addons     *[]CartProductAddonResponse `json:"addons,omitempty"`
	FinalPrice *float64                    `json:"final_price,omitempty"`
	Id         *openapi_types.UUID         `json:"id,omitempty"`
	ItemId     *openapi_types.UUID         `json:"item_id,omitempty"`
	Name       *string                     `json:"name,omitempty"`
	Price      *float64                    `json:"price,omitempty"`
	Quantity   *int                        `json:"quantity,omitempty"`
	TotalPrice *float64                    `json:"total_price,omitempty"`
	Vat        *float64                    `json:"vat,omitempty"`
}

// CreateActorRequest defines model for CreateActorRequest.
type CreateActorRequest struct {
	Email    openapi_types.Email     `json:"email"`
	FullName string                  `json:"full_name"`
	Password *string                 `json:"password,omitempty"`
	Role     *CreateActorRequestRole `json:"role,omitempty"`
}

// CreateActorRequestRole defines model for CreateActorRequest.Role.
type CreateActorRequestRole string

// CreateAreaRequest defines model for CreateAreaRequest.
type CreateAreaRequest struct {
	City CreateAreaRequestCity `json:"city"`
	Name string                `json:"name"`
}

// CreateAreaRequestCity defines model for CreateAreaRequest.City.
type CreateAreaRequestCity string

// CreateBranchRequest defines model for CreateBranchRequest.
type CreateBranchRequest struct {
	Address       string                  `json:"address"`
	City          CreateBranchRequestCity `json:"city"`
	ClosingTime   string                  `json:"closing_time"`
	ContactNumber string                  `json:"contact_number"`
	Name          string                  `json:"name"`
	OpeningTime   string                  `json:"opening_time"`
}

// CreateBranchRequestCity defines model for CreateBranchRequest.City.
type CreateBranchRequestCity string

// CreateCartRequest defines model for CreateCartRequest.
type CreateCartRequest struct {
	BranchId openapi_types.UUID `json:"branch_id"`
	CartId   openapi_types.UUID `json:"cart_id"`
}

// CreateCartResponse defines model for CreateCartResponse.
type CreateCartResponse struct {
	BranchId  *openapi_types.UUID `json:"branch_id,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	UpdatedAt *time.Time          `json:"updated_at,omitempty"`
}

// CreateCategoryRequest defines model for CreateCategoryRequest.
type CreateCategoryRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateDiscountRequest defines model for CreateDiscountRequest.
type CreateDiscountRequest struct {
	CategoryId  *openapi_types.UUID       `json:"category_id,omitempty"`
	Description *string                   `json:"description,omitempty"`
	ProductId   *openapi_types.UUID       `json:"product_id,omitempty"`
	Type        CreateDiscountRequestType `json:"type"`
	Value       float64                   `json:"value"`
}

// CreateDiscountRequestType defines model for CreateDiscountRequest.Type.
type CreateDiscountRequestType string

// CreateMerchantRequest defines model for CreateMerchantRequest.
type CreateMerchantRequest struct {
	Address       string                        `json:"address"`
	Category      CreateMerchantRequestCategory `json:"category"`
	ContactNumber string                        `json:"contact_number"`
	Name          string                        `json:"name"`
	Ntn           string                        `json:"ntn"`
}

// CreateMerchantRequestCategory defines model for CreateMerchantRequest.Category.
type CreateMerchantRequestCategory string

// CreateMerchantServiceZoneRequest defines model for CreateMerchantServiceZoneRequest.
type CreateMerchantServiceZoneRequest struct {
	BranchId openapi_types.UUID `json:"branch_id"`
	ZoneId   openapi_types.UUID `json:"zone_id"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	CartId          openapi_types.UUID            `json:"cart_id"`
	CustomerName    string                        `json:"customer_name"`
	CustomerPhone   string                        `json:"customer_phone"`
	DeliveryAddress string                        `json:"delivery_address"`
	PaymentType     CreateOrderRequestPaymentType `json:"payment_type"`
}

// CreateOrderRequestPaymentType defines model for CreateOrderRequest.PaymentType.
type CreateOrderRequestPaymentType string

// CreateProductAddonRequest defines model for CreateProductAddonRequest.
type CreateProductAddonRequest struct {
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

// CreateProductRequest defines model for CreateProductRequest.
type CreateProductRequest struct {
	BasePrice      float64            `json:"base_price"`
	CategoryId     openapi_types.UUID `json:"category_id"`
	Description    *string            `json:"description,omitempty"`
	ImageUrl       *string            `json:"image_url,omitempty"`
	Name           string             `json:"name"`
	TrackInventory *bool              `json:"track_inventory,omitempty"`
}

// CreateZoneRequest defines model for CreateZoneRequest.
type CreateZoneRequest struct {
	CoordinatesWkt string `json:"coordinates_wkt"`
	Name           string `json:"name"`
}

// DiscountResponse defines model for DiscountResponse.
type DiscountResponse struct {
	CategoryId  *openapi_types.UUID `json:"category_id,omitempty"`
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	MerchantId  *openapi_types.UUID `json:"merchant_id,omitempty"`
	ProductId   *openapi_types.UUID `json:"product_id,omitempty"`
	Type        *string             `json:"type,omitempty"`
	ValidFrom   *time.Time          `json:"valid_from,omitempty"`
	ValidTo     *time.Time          `json:"valid_to,omitempty"`
	Value       *float64            `json:"value,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code   *string `json:"code,omitempty"`
	Errors *string `json:"errors,omitempty"`
}

// InventoryItemResponse defines model for InventoryItemResponse.
type InventoryItemResponse struct {
	ProductId   *openapi_types.UUID `json:"product_id,omitempty"`
	ProductName *string             `json:"product_name,omitempty"`
	Quantity    *int                `json:"quantity,omitempty"`
}

// LoginActorRequest defines model for LoginActorRequest.
type LoginActorRequest struct {
	Email      openapi_types.Email `json:"email"`
	MerchantId openapi_types.UUID  `json:"merchant_id"`
	Password   string              `json:"password"`
}

// LoginActorResponse defines model for LoginActorResponse.
type LoginActorResponse struct {
	AccessToken           *string              `json:"access_token,omitempty"`
	AccessTokenExpiresAt  *time.Time           `json:"access_token_expires_at,omitempty"`
	Email                 *openapi_types.Email `json:"email,omitempty"`
	MerchantId            *openapi_types.UUID  `json:"merchant_id,omitempty"`
	RefreshToken          *string              `json:"refresh_token,omitempty"`
	RefreshTokenExpiresAt *time.Time           `json:"refresh_token_expires_at,omitempty"`
	Uid                   *openapi_types.UUID  `json:"uid,omitempty"`
}

// MerchantResponse defines model for MerchantResponse.
type MerchantResponse struct {
	Address       *string             `json:"address,omitempty"`
	Category      *string             `json:"category,omitempty"`
	ContactNumber *string             `json:"contact_number,omitempty"`
	CreatedAt     *time.Time          `json:"created_at,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	Logo          *string             `json:"logo,omitempty"`
	Name          *string             `json:"name,omitempty"`
	Ntn           *string             `json:"ntn,omitempty"`
	UpdatedAt     *time.Time          `json:"updated_at,omitempty"`
}

// MerchantServiceZoneResponse defines model for MerchantServiceZoneResponse.
type MerchantServiceZoneResponse struct {
	AreaCity           *string             `json:"area_city,omitempty"`
	AreaId             *openapi_types.UUID `json:"area_id,omitempty"`
	AreaName           *string             `json:"area_name,omitempty"`
	BranchId           *openapi_types.UUID `json:"branch_id,omitempty"`
	BranchName         *string             `json:"branch_name,omitempty"`
	CreatedAt          *time.Time          `json:"created_at,omitempty"`
	Id                 *openapi_types.UUID `json:"id,omitempty"`
	MerchantId         *openapi_types.UUID `json:"merchant_id,omitempty"`
	ZoneCoordinatesWkt *string             `json:"zone_coordinates_wkt,omitempty"`
	ZoneId             *openapi_types.UUID `json:"zone_id,omitempty"`
	ZoneName           *string             `json:"zone_name,omitempty"`
}

// OrderBillLineResponse defines model for OrderBillLineResponse.
type OrderBillLineResponse struct {
	AddonAmount    *float64            `json:"addon_amount,omitempty"`
	BaseAmount     *float64            `json:"base_amount,omitempty"`
	BasePrice      *float64            `json:"base_price,omitempty"`
	DiscountAmount *float64            `json:"discount_amount,omitempty"`
	FinalPrice     *float64            `json:"final_price,omitempty"`
	LineTotal      *float64            `json:"line_total,omitempty"`
	Name           *string             `json:"name,omitempty"`
	PaymentMethod  *string             `json:"payment_method,omitempty"`
	ProductId      *openapi_types.UUID `json:"product_id,omitempty"`
	Quantity       *int                `json:"quantity,omitempty"`
	TaxAmount      *float64            `json:"tax_amount,omitempty"`
	TotalPrice     *float64            `json:"total_price,omitempty"`
	Vat            *float64            `json:"vat,omitempty"`
}

// OrderBillResponse defines model for OrderBillResponse.
type OrderBillResponse struct {
	LineItems     *[]OrderBillLineResponse `json:"line_items,omitempty"`
	OrderId       *openapi_types.UUID      `json:"order_id,omitempty"`
	PaymentMethod *string                  `json:"payment_method,omitempty"`
	Subtotal      *float64                 `json:"subtotal,omitempty"`
	Total         *float64                 `json:"total,omitempty"`
	TotalTax      *float64                 `json:"total_tax,omitempty"`
	VatRate       *float64                 `json:"vat_rate,omitempty"`
}

// OrderDetailResponse defines model for OrderDetailResponse.
type OrderDetailResponse struct {
	ActorId         *openapi_types.UUID  `json:"actor_id,omitempty"`
	BranchId        *openapi_types.UUID  `json:"branch_id,omitempty"`
	CartId          *openapi_types.UUID  `json:"cart_id,omitempty"`
	CreatedAt       *time.Time           `json:"created_at,omitempty"`
	CustomerName    *string              `json:"customer_name,omitempty"`
	CustomerPhone   *string              `json:"customer_phone,omitempty"`
	DeliveryAddress *string              `json:"delivery_address,omitempty"`
	Id              *openapi_types.UUID  `json:"id,omitempty"`
	Items           *[]OrderLineResponse `json:"items,omitempty"`
	MerchantId      *openapi_types.UUID  `json:"merchant_id,omitempty"`
	PaymentType     *string              `json:"payment_type,omitempty"`
	Status          *string              `json:"status,omitempty"`
	TotalAmount     *float64             `json:"total_amount,omitempty"`
	UpdatedAt       *time.Time           `json:"updated_at,omitempty"`
	VatRate         *float64             `json:"vat_rate,omitempty"`
}

// OrderLineAddonResponse defines model for OrderLineAddonResponse.
type OrderLineAddonResponse struct {
	AddonId        *openapi_types.UUID `json:"addon_id,omitempty"`
	AddonName      *string             `json:"addon_name,omitempty"`
	AddonPrice     *float64            `json:"addon_price,omitempty"`
	LineAddonTotal *float64            `json:"line_addon_total,omitempty"`
	OrderId        *openapi_types.UUID `json:"order_id,omitempty"`
	ProductId      *openapi_types.UUID `json:"product_id,omitempty"`
	Quantity       *int                `json:"quantity,omitempty"`
}

// OrderLineResponse defines model for OrderLineResponse.
type OrderLineResponse struct {
	AddonAmount    *float64                  `json:"addon_amount,omitempty"`
	Addons         *[]OrderLineAddonResponse `json:"addons,omitempty"`
	BaseAmount     *float64                  `json:"base_amount,omitempty"`
	DiscountAmount *float64                  `json:"discount_amount,omitempty"`
	LineTotal      *float64                  `json:"line_total,omitempty"`
	OrderId        *openapi_types.UUID       `json:"order_id,omitempty"`
	Price          *float64                  `json:"price,omitempty"`
	Product        *ProductResponse          `json:"product,omitempty"`
	ProductId      *openapi_types.UUID       `json:"product_id,omitempty"`
	Quantity       *int                      `json:"quantity,omitempty"`
	TaxAmount      *float64                  `json:"tax_amount,omitempty"`
}

// OrderSummaryResponse defines model for OrderSummaryResponse.
type OrderSummaryResponse struct {
	ActorId         *openapi_types.UUID `json:"actor_id,omitempty"`
	BranchId        *openapi_types.UUID `json:"branch_id,omitempty"`
	CartId          *openapi_types.UUID `json:"cart_id,omitempty"`
	CreatedAt       *time.Time          `json:"created_at,omitempty"`
	CustomerName    *string             `json:"customer_name,omitempty"`
	CustomerPhone   *string             `json:"customer_phone,omitempty"`
	DeliveryAddress *string             `json:"delivery_address,omitempty"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	MerchantId      *openapi_types.UUID `json:"merchant_id,omitempty"`
	PaymentType     *string             `json:"payment_type,omitempty"`
	Status          *string             `json:"status,omitempty"`
	TotalAmount     *float64            `json:"total_amount,omitempty"`
	UpdatedAt       *time.Time          `json:"updated_at,omitempty"`
	VatRate         *float64            `json:"vat_rate,omitempty"`
}

// ProductAddonResponse defines model for ProductAddonResponse.
type ProductAddonResponse struct {
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Name      *string             `json:"name,omitempty"`
	Price     *float64            `json:"price,omitempty"`
	ProductId *openapi_types.UUID `json:"product_id,omitempty"`
}

// ProductCategoryResponse defines model for ProductCategoryResponse.
type ProductCategoryResponse struct {
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	MerchantId  *openapi_types.UUID `json:"merchant_id,omitempty"`
	Name        *string             `json:"name,omitempty"`
}

// ProductDetailResponse defines model for ProductDetailResponse.
type ProductDetailResponse struct {
	BasePrice      *float64            `json:"base_price,omitempty"`
	CategoryId     *openapi_types.UUID `json:"category_id,omitempty"`
	CategoryName   *string             `json:"category_name,omitempty"`
	CreatedAt      *time.Time          `json:"created_at,omitempty"`
	Description    *string             `json:"description,omitempty"`
	Id             *openapi_types.UUID `json:"id,omitempty"`
	ImageUrl       *string             `json:"image_url,omitempty"`
	IsActive       *bool               `json:"is_active,omitempty"`
	MerchantId     *openapi_types.UUID `json:"merchant_id,omitempty"`
	Name           *string             `json:"name,omitempty"`
	TrackInventory *bool               `json:"track_inventory,omitempty"`
	UpdatedAt      *time.Time          `json:"updated_at,omitempty"`
}

// ProductInventoryResponse defines model for ProductInventoryResponse.
type ProductInventoryResponse struct {
	BranchId  *openapi_types.UUID `json:"branch_id,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	ProductId *openapi_types.UUID `json:"product_id,omitempty"`
	Quantity  *int                `json:"quantity,omitempty"`
	UpdatedAt *time.Time          `json:"updated_at,omitempty"`
}

// ProductResponse defines model for ProductResponse.
type ProductResponse struct {
	BasePrice      *float64            `json:"base_price,omitempty"`
	CategoryId     *openapi_types.UUID `json:"category_id,omitempty"`
	CreatedAt      *time.Time          `json:"created_at,omitempty"`
	Description    *string             `json:"description,omitempty"`
	Id             *openapi_types.UUID `json:"id,omitempty"`
	ImageUrl       *string             `json:"image_url,omitempty"`
	IsActive       *bool               `json:"is_active,omitempty"`
	MerchantId     *openapi_types.UUID `json:"merchant_id,omitempty"`
	Name           *string             `json:"name,omitempty"`
	TrackInventory *bool               `json:"track_inventory,omitempty"`
	UpdatedAt      *time.Time          `json:"updated_at,omitempty"`
}

// ProductWithAddonsResponse defines model for ProductWithAddonsResponse.
type ProductWithAddonsResponse struct {
	Addons         *[]ProductAddonResponse `json:"addons,omitempty"`
	BasePrice      *float64                `json:"base_price,omitempty"`
	CategoryId     *openapi_types.UUID     `json:"category_id,omitempty"`
	CreatedAt      *time.Time              `json:"created_at,omitempty"`
	Description    *string                 `json:"description,omitempty"`
	Id             *openapi_types.UUID     `json:"id,omitempty"`
	ImageUrl       *string                 `json:"image_url,omitempty"`
	IsActive       *bool                   `json:"is_active,omitempty"`
	MerchantId     *openapi_types.UUID     `json:"merchant_id,omitempty"`
	Name           *string                 `json:"name,omitempty"`
	TrackInventory *bool                   `json:"track_inventory,omitempty"`
	UpdatedAt      *time.Time              `json:"updated_at,omitempty"`
}

// RenewAccessTokenRequest defines model for RenewAccessTokenRequest.
type RenewAccessTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RenewAccessTokenResponse defines model for RenewAccessTokenResponse.
type RenewAccessTokenResponse struct {
	AccessToken          *string    `json:"access_token,omitempty"`
	AccessTokenExpiresAt *time.Time `json:"access_token_expires_at,omitempty"`
}

// RoleResponse defines model for RoleResponse.
type RoleResponse struct {
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	MerchantId  *openapi_types.UUID `json:"merchant_id,omitempty"`
	RoleType    *string             `json:"role_type,omitempty"`
}

// SalesReportResponse defines model for SalesReportResponse.
type SalesReportResponse struct {
	Month          *int     `json:"month,omitempty"`
	ProfitEstimate *float64 `json:"profit_estimate,omitempty"`
	TotalDiscount  *float64 `json:"total_discount,omitempty"`
	TotalSales     *float64 `json:"total_sales,omitempty"`
	TotalTax       *float64 `json:"total_tax,omitempty"`
	Year           *int     `json:"year,omitempty"`
}

// ServiceZoneCoverageCheckRequest defines model for ServiceZoneCoverageCheckRequest.
type ServiceZoneCoverageCheckRequest struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

// ServiceZoneCoverageCheckResponse defines model for ServiceZoneCoverageCheckResponse.
type ServiceZoneCoverageCheckResponse struct {
	AreaCity   *string             `json:"area_city,omitempty"`
	AreaId     *openapi_types.UUID `json:"area_id,omitempty"`
	AreaName   *string             `json:"area_name,omitempty"`
	BranchId   *openapi_types.UUID `json:"branch_id,omitempty"`
	BranchName *string             `json:"branch_name,omitempty"`
	Covered    *bool               `json:"covered,omitempty"`
	MerchantId *openapi_types.UUID `json:"merchant_id,omitempty"`
	ZoneId     *openapi_types.UUID `json:"zone_id,omitempty"`
	ZoneName   *string             `json:"zone_name,omitempty"`
}

// UpdateCartItemRequest defines model for UpdateCartItemRequest.
type UpdateCartItemRequest struct {
	Quantity int `json:"quantity"`
}

// UpdateMerchantRequest defines model for UpdateMerchantRequest.
type UpdateMerchantRequest struct {
	Address       string                        `json:"address"`
	Category      UpdateMerchantRequestCategory `json:"category"`
	ContactNumber string                        `json:"contact_number"`
	Name          string                        `json:"name"`
	Ntn           string                        `json:"ntn"`
}

// UpdateMerchantRequestCategory defines model for UpdateMerchantRequest.Category.
type UpdateMerchantRequestCategory string

// UpdateOrderStatusRequest defines model for UpdateOrderStatusRequest.
type UpdateOrderStatusRequest struct {
	Status UpdateOrderStatusRequestStatus `json:"status"`
}

// UpdateOrderStatusRequestStatus defines model for UpdateOrderStatusRequest.Status.
type UpdateOrderStatusRequestStatus string

// UpsertInventoryRequest defines model for UpsertInventoryRequest.
type UpsertInventoryRequest struct {
	BranchId  openapi_types.UUID `json:"branch_id"`
	ProductId openapi_types.UUID `json:"product_id"`
	Quantity  int                `json:"quantity"`
}

// ZoneResponse defines model for ZoneResponse.
type ZoneResponse struct {
	AreaId         *openapi_types.UUID `json:"area_id,omitempty"`
	CoordinatesWkt *string             `json:"coordinates_wkt,omitempty"`
	CreatedAt      *time.Time          `json:"created_at,omitempty"`
	Id             *openapi_types.UUID `json:"id,omitempty"`
	Name           *string             `json:"name,omitempty"`
}

// GetCartDetailParams defines parameters for GetCartDetail.
type GetCartDetailParams struct {
	PaymentMethod *GetCartDetailParamsPaymentMethod `form:"payment_method,omitempty" json:"payment_method,omitempty"`
}

// GetCartDetailParamsPaymentMethod defines parameters for GetCartDetail.
type GetCartDetailParamsPaymentMethod string

// GetMonthlySalesReportParams defines parameters for GetMonthlySalesReport.
type GetMonthlySalesReportParams struct {
	Month int `form:"month" json:"month"`
	Year  int `form:"year" json:"year"`
}

// CreateActorJSONRequestBody defines body for CreateActor for application/json ContentType.
type CreateActorJSONRequestBody = CreateActorRequest

// CreateAreaJSONRequestBody defines body for CreateArea for application/json ContentType.
type CreateAreaJSONRequestBody = CreateAreaRequest

// CreateZoneJSONRequestBody defines body for CreateZone for application/json ContentType.
type CreateZoneJSONRequestBody = CreateZoneRequest

// CreateCartJSONRequestBody defines body for CreateCart for application/json ContentType.
type CreateCartJSONRequestBody = CreateCartRequest

// AddItemToCartJSONRequestBody defines body for AddItemToCart for application/json ContentType.
type AddItemToCartJSONRequestBody = AddCartItemRequest

// UpdateCartItemJSONRequestBody defines body for UpdateCartItem for application/json ContentType.
type UpdateCartItemJSONRequestBody = UpdateCartItemRequest

// LoginActorJSONRequestBody defines body for LoginActor for application/json ContentType.
type LoginActorJSONRequestBody = LoginActorRequest

// UpdateMerchantJSONRequestBody defines body for UpdateMerchant for application/json ContentType.
type UpdateMerchantJSONRequestBody = UpdateMerchantRequest

// CreateBranchByMerchantJSONRequestBody defines body for CreateBranchByMerchant for application/json ContentType.
type CreateBranchByMerchantJSONRequestBody = CreateBranchRequest

// CreateProductCategoryByMerchantJSONRequestBody defines body for CreateProductCategoryByMerchant for application/json ContentType.
type CreateProductCategoryByMerchantJSONRequestBody = CreateCategoryRequest

// CreateDiscountByMerchantJSONRequestBody defines body for CreateDiscountByMerchant for application/json ContentType.
type CreateDiscountByMerchantJSONRequestBody = CreateDiscountRequest

// UpsertInventoryByMerchantJSONRequestBody defines body for UpsertInventoryByMerchant for application/json ContentType.
type UpsertInventoryByMerchantJSONRequestBody = UpsertInventoryRequest

// CreateProductByMerchantJSONRequestBody defines body for CreateProductByMerchant for application/json ContentType.
type CreateProductByMerchantJSONRequestBody = CreateProductRequest

// CreateMerchantServiceZoneByMerchantJSONRequestBody defines body for CreateMerchantServiceZoneByMerchant for application/json ContentType.
type CreateMerchantServiceZoneByMerchantJSONRequestBody = CreateMerchantServiceZoneRequest

// CheckMerchantServiceZoneCoverageJSONRequestBody defines body for CheckMerchantServiceZoneCoverage for application/json ContentType.
type CheckMerchantServiceZoneCoverageJSONRequestBody = ServiceZoneCoverageCheckRequest

// CreateMerchantJSONRequestBody defines body for CreateMerchant for application/json ContentType.
type CreateMerchantJSONRequestBody = CreateMerchantRequest

// BootstrapMerchantActorJSONRequestBody defines body for BootstrapMerchantActor for application/json ContentType.
type BootstrapMerchantActorJSONRequestBody = BootstrapActorRequest

// PlaceOrderFromCartJSONRequestBody defines body for PlaceOrderFromCart for application/json ContentType.
type PlaceOrderFromCartJSONRequestBody = CreateOrderRequest

// UpdateOrderStatusJSONRequestBody defines body for UpdateOrderStatus for application/json ContentType.
type UpdateOrderStatusJSONRequestBody = UpdateOrderStatusRequest

// AddProductAddonByMerchantJSONRequestBody defines body for AddProductAddonByMerchant for application/json ContentType.
type AddProductAddonByMerchantJSONRequestBody = CreateProductAddonRequest

// RenewAccessTokenJSONRequestBody defines body for RenewAccessToken for application/json ContentType.
type RenewAccessTokenJSONRequestBody = RenewAccessTokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/v1/actor/{uid})
	GetActorByUIDLegacy(w http.ResponseWriter, r *http.Request, uid string)

	// (POST /api/v1/actors)
	CreateActor(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/actors/me)
	GetAuthenticatedActor(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/actors/{uid})
	GetActorByUID(w http.ResponseWriter, r *http.Request, uid string)

	// (GET /api/v1/areas)
	ListAreas(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/areas)
	CreateArea(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/areas/{area_id}/zones)
	ListZonesByArea(w http.ResponseWriter, r *http.Request, areaId string)

	// (POST /api/v1/areas/{area_id}/zones)
	CreateZone(w http.ResponseWriter, r *http.Request, areaId string)

	// (POST /api/v1/carts)
	CreateCart(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/carts/{cart_id})
	GetCartDetail(w http.ResponseWriter, r *http.Request, cartId string, params GetCartDetailParams)

	// (POST /api/v1/carts/{cart_id}/items)
	AddItemToCart(w http.ResponseWriter, r *http.Request, cartId string)

	// (DELETE /api/v1/carts/{cart_id}/items/{item_id})
	DeleteCartItem(w http.ResponseWriter, r *http.Request, cartId string, itemId string)

	// (PATCH /api/v1/carts/{cart_id}/items/{item_id})
	UpdateCartItem(w http.ResponseWriter, r *http.Request, cartId string, itemId string)

	// (POST /api/v1/login)
	LoginActor(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/merchant)
	GetMerchant(w http.ResponseWriter, r *http.Request)

	// (PATCH /api/v1/merchant)
	UpdateMerchant(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/merchant/actors)
	ListActorsByMerchant(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/merchant/branches)
	ListBranchesByMerchant(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/merchant/branches)
	CreateBranchByMerchant(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/merchant/branches/{branch_id}/availability)
	GetBranchAvailability(w http.ResponseWriter, r *http.Request, branchId string)

	// (GET /api/v1/merchant/categories)
	ListProductCategoriesByMerchant(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/merchant/categories)
	CreateProductCategoryByMerchant(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/merchant/discounts)
	ListDiscountsByMerchant(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/merchant/discounts)
	CreateDiscountByMerchant(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/merchant/employees)
	ListEmployeesByMerchant(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/merchant/inventory)
	ListInventoryByMerchant(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/merchant/inventory)
	UpsertInventoryByMerchant(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/merchant/orders)
	ListOrdersByMerchant(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/merchant/products)
	ListProductsByMerchant(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/merchant/products)
	CreateProductByMerchant(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/merchant/reports/sales)
	GetMonthlySalesReport(w http.ResponseWriter, r *http.Request, params GetMonthlySalesReportParams)

	// (GET /api/v1/merchant/roles)
	ListRolesByMerchant(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/merchant/service-zones)
	ListMerchantServiceZonesByMerchant(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/merchant/service-zones)
	CreateMerchantServiceZoneByMerchant(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/merchant/service-zones/check)
	CheckMerchantServiceZoneCoverage(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/merchants)
	ListMerchants(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/merchants)
	CreateMerchant(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/merchants/{merchant_id}/bootstrap-actor)
	BootstrapMerchantActor(w http.ResponseWriter, r *http.Request, merchantId string)

	// (POST /api/v1/orders)
	PlaceOrderFromCart(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/orders/{order_id})
	GetOrderDetail(w http.ResponseWriter, r *http.Request, orderId string)

	// (PATCH /api/v1/orders/{order_id})
	UpdateOrderStatus(w http.ResponseWriter, r *http.Request, orderId string)

	// (GET /api/v1/products/{product_id})
	GetProductDetail(w http.ResponseWriter, r *http.Request, productId string)

	// (GET /api/v1/products/{product_id}/addons)
	ListProductAddonsByProduct(w http.ResponseWriter, r *http.Request, productId string)

	// (POST /api/v1/products/{product_id}/addons)
	AddProductAddonByMerchant(w http.ResponseWriter, r *http.Request, productId string)

	// (POST /api/v1/renew-token)
	RenewAccessToken(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http-tools.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /api/v1/actor/{uid})
func (_ Unimplemented) GetActorByUIDLegacy(w http.ResponseWriter, r *http.Request, uid string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/actors)
func (_ Unimplemented) CreateActor(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/actors/me)
func (_ Unimplemented) GetAuthenticatedActor(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/actors/{uid})
func (_ Unimplemented) GetActorByUID(w http.ResponseWriter, r *http.Request, uid string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/areas)
func (_ Unimplemented) ListAreas(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/areas)
func (_ Unimplemented) CreateArea(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/areas/{area_id}/zones)
func (_ Unimplemented) ListZonesByArea(w http.ResponseWriter, r *http.Request, areaId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/areas/{area_id}/zones)
func (_ Unimplemented) CreateZone(w http.ResponseWriter, r *http.Request, areaId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/carts)
func (_ Unimplemented) CreateCart(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/carts/{cart_id})
func (_ Unimplemented) GetCartDetail(w http.ResponseWriter, r *http.Request, cartId string, params GetCartDetailParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/carts/{cart_id}/items)
func (_ Unimplemented) AddItemToCart(w http.ResponseWriter, r *http.Request, cartId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/v1/carts/{cart_id}/items/{item_id})
func (_ Unimplemented) DeleteCartItem(w http.ResponseWriter, r *http.Request, cartId string, itemId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /api/v1/carts/{cart_id}/items/{item_id})
func (_ Unimplemented) UpdateCartItem(w http.ResponseWriter, r *http.Request, cartId string, itemId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/login)
func (_ Unimplemented) LoginActor(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/merchant)
func (_ Unimplemented) GetMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /api/v1/merchant)
func (_ Unimplemented) UpdateMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/merchant/actors)
func (_ Unimplemented) ListActorsByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/merchant/branches)
func (_ Unimplemented) ListBranchesByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/merchant/branches)
func (_ Unimplemented) CreateBranchByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/merchant/branches/{branch_id}/availability)
func (_ Unimplemented) GetBranchAvailability(w http.ResponseWriter, r *http.Request, branchId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/merchant/categories)
func (_ Unimplemented) ListProductCategoriesByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/merchant/categories)
func (_ Unimplemented) CreateProductCategoryByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/merchant/discounts)
func (_ Unimplemented) ListDiscountsByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/merchant/discounts)
func (_ Unimplemented) CreateDiscountByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/merchant/employees)
func (_ Unimplemented) ListEmployeesByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/merchant/inventory)
func (_ Unimplemented) ListInventoryByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/merchant/inventory)
func (_ Unimplemented) UpsertInventoryByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/merchant/orders)
func (_ Unimplemented) ListOrdersByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/merchant/products)
func (_ Unimplemented) ListProductsByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/merchant/products)
func (_ Unimplemented) CreateProductByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/merchant/reports/sales)
func (_ Unimplemented) GetMonthlySalesReport(w http.ResponseWriter, r *http.Request, params GetMonthlySalesReportParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/merchant/roles)
func (_ Unimplemented) ListRolesByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/merchant/service-zones)
func (_ Unimplemented) ListMerchantServiceZonesByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/merchant/service-zones)
func (_ Unimplemented) CreateMerchantServiceZoneByMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/merchant/service-zones/check)
func (_ Unimplemented) CheckMerchantServiceZoneCoverage(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/merchants)
func (_ Unimplemented) ListMerchants(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/merchants)
func (_ Unimplemented) CreateMerchant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/merchants/{merchant_id}/bootstrap-actor)
func (_ Unimplemented) BootstrapMerchantActor(w http.ResponseWriter, r *http.Request, merchantId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/orders)
func (_ Unimplemented) PlaceOrderFromCart(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/orders/{order_id})
func (_ Unimplemented) GetOrderDetail(w http.ResponseWriter, r *http.Request, orderId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /api/v1/orders/{order_id})
func (_ Unimplemented) UpdateOrderStatus(w http.ResponseWriter, r *http.Request, orderId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/products/{product_id})
func (_ Unimplemented) GetProductDetail(w http.ResponseWriter, r *http.Request, productId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/products/{product_id}/addons)
func (_ Unimplemented) ListProductAddonsByProduct(w http.ResponseWriter, r *http.Request, productId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/products/{product_id}/addons)
func (_ Unimplemented) AddProductAddonByMerchant(w http.ResponseWriter, r *http.Request, productId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/renew-token)
func (_ Unimplemented) RenewAccessToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetActorByUIDLegacy operation middleware
func (siw *ServerInterfaceWrapper) GetActorByUIDLegacy(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uid" -------------
	var uid string

	err = runtime.BindStyledParameterWithOptions("simple", "uid", chi.URLParam(r, "uid"), &uid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActorByUIDLegacy(w, r, uid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateActor operation middleware
func (siw *ServerInterfaceWrapper) CreateActor(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateActor(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthenticatedActor operation middleware
func (siw *ServerInterfaceWrapper) GetAuthenticatedActor(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthenticatedActor(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetActorByUID operation middleware
func (siw *ServerInterfaceWrapper) GetActorByUID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uid" -------------
	var uid string

	err = runtime.BindStyledParameterWithOptions("simple", "uid", chi.URLParam(r, "uid"), &uid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActorByUID(w, r, uid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAreas operation middleware
func (siw *ServerInterfaceWrapper) ListAreas(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAreas(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateArea operation middleware
func (siw *ServerInterfaceWrapper) CreateArea(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateArea(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListZonesByArea operation middleware
func (siw *ServerInterfaceWrapper) ListZonesByArea(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "area_id" -------------
	var areaId string

	err = runtime.BindStyledParameterWithOptions("simple", "area_id", chi.URLParam(r, "area_id"), &areaId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "area_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListZonesByArea(w, r, areaId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateZone operation middleware
func (siw *ServerInterfaceWrapper) CreateZone(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "area_id" -------------
	var areaId string

	err = runtime.BindStyledParameterWithOptions("simple", "area_id", chi.URLParam(r, "area_id"), &areaId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "area_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateZone(w, r, areaId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCart operation middleware
func (siw *ServerInterfaceWrapper) CreateCart(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCartDetail operation middleware
func (siw *ServerInterfaceWrapper) GetCartDetail(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "cart_id" -------------
	var cartId string

	err = runtime.BindStyledParameterWithOptions("simple", "cart_id", chi.URLParam(r, "cart_id"), &cartId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cart_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCartDetailParams

	// ------------- Optional query parameter "payment_method" -------------

	err = runtime.BindQueryParameter("form", true, false, "payment_method", r.URL.Query(), &params.PaymentMethod)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "payment_method", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCartDetail(w, r, cartId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddItemToCart operation middleware
func (siw *ServerInterfaceWrapper) AddItemToCart(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "cart_id" -------------
	var cartId string

	err = runtime.BindStyledParameterWithOptions("simple", "cart_id", chi.URLParam(r, "cart_id"), &cartId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cart_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddItemToCart(w, r, cartId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCartItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteCartItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "cart_id" -------------
	var cartId string

	err = runtime.BindStyledParameterWithOptions("simple", "cart_id", chi.URLParam(r, "cart_id"), &cartId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cart_id", Err: err})
		return
	}

	// ------------- Path parameter "item_id" -------------
	var itemId string

	err = runtime.BindStyledParameterWithOptions("simple", "item_id", chi.URLParam(r, "item_id"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCartItem(w, r, cartId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCartItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateCartItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "cart_id" -------------
	var cartId string

	err = runtime.BindStyledParameterWithOptions("simple", "cart_id", chi.URLParam(r, "cart_id"), &cartId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cart_id", Err: err})
		return
	}

	// ------------- Path parameter "item_id" -------------
	var itemId string

	err = runtime.BindStyledParameterWithOptions("simple", "item_id", chi.URLParam(r, "item_id"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCartItem(w, r, cartId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginActor operation middleware
func (siw *ServerInterfaceWrapper) LoginActor(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginActor(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMerchant operation middleware
func (siw *ServerInterfaceWrapper) GetMerchant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMerchant operation middleware
func (siw *ServerInterfaceWrapper) UpdateMerchant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListActorsByMerchant operation middleware
func (siw *ServerInterfaceWrapper) ListActorsByMerchant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListActorsByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBranchesByMerchant operation middleware
func (siw *ServerInterfaceWrapper) ListBranchesByMerchant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBranchesByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBranchByMerchant operation middleware
func (siw *ServerInterfaceWrapper) CreateBranchByMerchant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBranchByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBranchAvailability operation middleware
func (siw *ServerInterfaceWrapper) GetBranchAvailability(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "branch_id" -------------
	var branchId string

	err = runtime.BindStyledParameterWithOptions("simple", "branch_id", chi.URLParam(r, "branch_id"), &branchId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "branch_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBranchAvailability(w, r, branchId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProductCategoriesByMerchant operation middleware
func (siw *ServerInterfaceWrapper) ListProductCategoriesByMerchant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProductCategoriesByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProductCategoryByMerchant operation middleware
func (siw *ServerInterfaceWrapper) CreateProductCategoryByMerchant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProductCategoryByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDiscountsByMerchant operation middleware
func (siw *ServerInterfaceWrapper) ListDiscountsByMerchant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDiscountsByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDiscountByMerchant operation middleware
func (siw *ServerInterfaceWrapper) CreateDiscountByMerchant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDiscountByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEmployeesByMerchant operation middleware
func (siw *ServerInterfaceWrapper) ListEmployeesByMerchant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEmployeesByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInventoryByMerchant operation middleware
func (siw *ServerInterfaceWrapper) ListInventoryByMerchant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInventoryByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpsertInventoryByMerchant operation middleware
func (siw *ServerInterfaceWrapper) UpsertInventoryByMerchant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpsertInventoryByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrdersByMerchant operation middleware
func (siw *ServerInterfaceWrapper) ListOrdersByMerchant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrdersByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProductsByMerchant operation middleware
func (siw *ServerInterfaceWrapper) ListProductsByMerchant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProductsByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProductByMerchant operation middleware
func (siw *ServerInterfaceWrapper) CreateProductByMerchant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProductByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMonthlySalesReport operation middleware
func (siw *ServerInterfaceWrapper) GetMonthlySalesReport(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMonthlySalesReportParams

	// ------------- Required query parameter "month" -------------

	if paramValue := r.URL.Query().Get("month"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "month"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "month", r.URL.Query(), &params.Month)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "month", Err: err})
		return
	}

	// ------------- Required query parameter "year" -------------

	if paramValue := r.URL.Query().Get("year"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "year", r.URL.Query(), &params.Year)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMonthlySalesReport(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRolesByMerchant operation middleware
func (siw *ServerInterfaceWrapper) ListRolesByMerchant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRolesByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMerchantServiceZonesByMerchant operation middleware
func (siw *ServerInterfaceWrapper) ListMerchantServiceZonesByMerchant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMerchantServiceZonesByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMerchantServiceZoneByMerchant operation middleware
func (siw *ServerInterfaceWrapper) CreateMerchantServiceZoneByMerchant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMerchantServiceZoneByMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckMerchantServiceZoneCoverage operation middleware
func (siw *ServerInterfaceWrapper) CheckMerchantServiceZoneCoverage(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckMerchantServiceZoneCoverage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMerchants operation middleware
func (siw *ServerInterfaceWrapper) ListMerchants(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMerchants(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMerchant operation middleware
func (siw *ServerInterfaceWrapper) CreateMerchant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMerchant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BootstrapMerchantActor operation middleware
func (siw *ServerInterfaceWrapper) BootstrapMerchantActor(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "merchant_id" -------------
	var merchantId string

	err = runtime.BindStyledParameterWithOptions("simple", "merchant_id", chi.URLParam(r, "merchant_id"), &merchantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "merchant_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BootstrapMerchantActor(w, r, merchantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlaceOrderFromCart operation middleware
func (siw *ServerInterfaceWrapper) PlaceOrderFromCart(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlaceOrderFromCart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrderDetail operation middleware
func (siw *ServerInterfaceWrapper) GetOrderDetail(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order_id" -------------
	var orderId string

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", chi.URLParam(r, "order_id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrderDetail(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateOrderStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrderStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order_id" -------------
	var orderId string

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", chi.URLParam(r, "order_id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOrderStatus(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProductDetail operation middleware
func (siw *ServerInterfaceWrapper) GetProductDetail(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "product_id" -------------
	var productId string

	err = runtime.BindStyledParameterWithOptions("simple", "product_id", chi.URLParam(r, "product_id"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "product_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProductDetail(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProductAddonsByProduct operation middleware
func (siw *ServerInterfaceWrapper) ListProductAddonsByProduct(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "product_id" -------------
	var productId string

	err = runtime.BindStyledParameterWithOptions("simple", "product_id", chi.URLParam(r, "product_id"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "product_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProductAddonsByProduct(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddProductAddonByMerchant operation middleware
func (siw *ServerInterfaceWrapper) AddProductAddonByMerchant(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "product_id" -------------
	var productId string

	err = runtime.BindStyledParameterWithOptions("simple", "product_id", chi.URLParam(r, "product_id"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "product_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddProductAddonByMerchant(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenewAccessToken operation middleware
func (siw *ServerInterfaceWrapper) RenewAccessToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenewAccessToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/actor/{uid}", wrapper.GetActorByUIDLegacy)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/actors", wrapper.CreateActor)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/actors/me", wrapper.GetAuthenticatedActor)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/actors/{uid}", wrapper.GetActorByUID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/areas", wrapper.ListAreas)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/areas", wrapper.CreateArea)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/areas/{area_id}/zones", wrapper.ListZonesByArea)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/areas/{area_id}/zones", wrapper.CreateZone)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/carts", wrapper.CreateCart)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/carts/{cart_id}", wrapper.GetCartDetail)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/carts/{cart_id}/items", wrapper.AddItemToCart)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/carts/{cart_id}/items/{item_id}", wrapper.DeleteCartItem)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/carts/{cart_id}/items/{item_id}", wrapper.UpdateCartItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/login", wrapper.LoginActor)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/merchant", wrapper.GetMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/merchant", wrapper.UpdateMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/merchant/actors", wrapper.ListActorsByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/merchant/branches", wrapper.ListBranchesByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/merchant/branches", wrapper.CreateBranchByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/merchant/branches/{branch_id}/availability", wrapper.GetBranchAvailability)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/merchant/categories", wrapper.ListProductCategoriesByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/merchant/categories", wrapper.CreateProductCategoryByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/merchant/discounts", wrapper.ListDiscountsByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/merchant/discounts", wrapper.CreateDiscountByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/merchant/employees", wrapper.ListEmployeesByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/merchant/inventory", wrapper.ListInventoryByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/merchant/inventory", wrapper.UpsertInventoryByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/merchant/orders", wrapper.ListOrdersByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/merchant/products", wrapper.ListProductsByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/merchant/products", wrapper.CreateProductByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/merchant/reports/sales", wrapper.GetMonthlySalesReport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/merchant/roles", wrapper.ListRolesByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/merchant/service-zones", wrapper.ListMerchantServiceZonesByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/merchant/service-zones", wrapper.CreateMerchantServiceZoneByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/merchant/service-zones/check", wrapper.CheckMerchantServiceZoneCoverage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/merchants", wrapper.ListMerchants)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/merchants", wrapper.CreateMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/merchants/{merchant_id}/bootstrap-actor", wrapper.BootstrapMerchantActor)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/orders", wrapper.PlaceOrderFromCart)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/orders/{order_id}", wrapper.GetOrderDetail)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/orders/{order_id}", wrapper.UpdateOrderStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/products/{product_id}", wrapper.GetProductDetail)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/products/{product_id}/addons", wrapper.ListProductAddonsByProduct)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/products/{product_id}/addons", wrapper.AddProductAddonByMerchant)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/renew-token", wrapper.RenewAccessToken)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+wdXZPbtvGveNg8tDM6U7bbh+jtzk46bpzGYzuTmd6oHBy5kpAjARoEz1au+u8dgKT4",
	"BZCAjqQ+4rc7EQT2G4vdxfLR8WkUUwKEJ87i0Un8DURI/nntc8reM7rCIXyAJKYkAfF7zGgMjGOQoyBC",
	"OBR/rCiLEHcW+S8zh29jcBZOwhkma2c3c1ZpGHoERXKW1lOceMjn+KH69I7SEBARj0OUcC+ka0xqiwWI",
	"wxXHEagWjID5G0S4h4PaS2mKA9X41Gjcbv8LvfsdfC7evA6C14jxtxyiD/A5hYS3KYWCgBIPB/IfzCFK",
	"jIDKf0CMoa34P8CJT1NzpGJGg9Q3Hv45RYRjvq1wARMOa2AScwafU8wgcBa31Zkr7y1V5GGA9CLk15cr",
	"YfEZIA6Bh7g5zw3R1Iihirc3lPKEMxRLhdCydzBFiFGSfKEsUD5kNJRvAUkjwYNCxJ2ZA1Ec0i0Iqvhp",
	"wmkErMKMCoZVHpagzPbw7gHIl1Nx9IYh4m+uHxAO0R0OMd/q+Xsnx5oKYD5aSx4/pAkma08KgHJAyhgQ",
	"rh+AE4/GQNR2xtZmiJk6wREP/qDEWNok+npioiBgkCRqzLWK1EszSjjyuUfS6A7Y1Mo4KEO0gtPLqTQO",
	"LDFUMVDsA2+AIxx2WDzEjPEp7L0Y/B2DlbNw/uKWm7ab79iuXDcfu19ZmpNtJNQhAr6haqOSG/L6xtS3",
	"1vvspepSza0qSe845ahuFQOa3oUVWuYiJ14XY72YYR+s3nhoMkw7/gFxjyFuNr2WuU0it3U0KhhmAFMA",
	"ic9wzDElamsVWLgJivcfUJg+DeHMq9EhKwTmOL6IEthcLK+Fs9UB9BNtibmQ9sDZaegpOUgl67gr9HKF",
	"iaWimRpyC1kYgLbdEnKIQTE1JUquyg3yz+EkLvX4S1dfg37hoBSA/YQY8jfYmTnv0IYyUIDS5apXYczB",
	"83VHkAy6wrvSH9F6nSsr2JuOF3xFUSyY47x8uXg1l84258CIs3D++9fb+Yvl7fzq++X/Xt7Or14t/7a4",
	"nV/9I/vpO5WMGLhtxu5QCdr8+8X8iaCpmVOQtwV4Tt0GUA3y6bkqbJ+Wp3anD3PPrIFiuUw5SR/EwxyY",
	"RnTMB/KIc5Q5rCnbahnV5whZ2AE94UvnTWeicjCN3fMeqC1dnsKNK6zMKkTCbMfAfCAcrdVmxsrHq1JL",
	"Pi3e11Pt53wDOcxw5hStosUg4Shl2Z4UbxCLkDNz7tA9sK3akD7B0hFOjPcPMbZmqArgWyD0U+sjsAfs",
	"w38ogYGs0x+UwEHWqXhxVllQj8AvLADWoSHmh9fCx+gI5xQj4o06SCJULMQPwLZel5QVx9ymAvmIZSY5",
	"2fQ7OgVqjekUIDRRayGip27dS9cQeZiTh0LAs/d7odMLLErAyqUe2qDiCK3BS1loZwQ4Q/69h8kDEJ4b",
	"owBWKA25s1ihMIFZK/bUEo4SkVlBzgo59DTttAA+pSzABHFIvC/3/Klb36w1oQqu/hiGLdsO8UIGCn3Y",
	"RggP3JJVuy4OvBWjkTnK2TucWr3xhPjND4yJ46iWyzRQ4wbivcQwZv220KruSJEl3YvhWpW2DQ+9o2tM",
	"BjufW0ud/sTe0OPqzIqszLIHNW1AyfchSTxO70GtbtUBHnyNMYPESp9HpB6DFYNk0wF9bcRB4B+e/i39",
	"44PSNhUH+cQyMyFd0yGc7aGOkkrXWktzBsjT5sTkU0MyyLFalAfOb47HTVulk6cGE//E/FySj7VIv8vD",
	"yA0Ow3e4k9myusIq8yJ9N/s3bJzffbGG1TL28fkQE/Bscm0dgWXTdOEQWZyZw9FXO+JMG9TfS59e8iTt",
	"9zkao2SNWqYVmRoqBpp7GL2sOyQja8UXjr5OlYuVRGxn2lEY/rJyFrcGHPiYRhFi2woDVMlNS7Z2s7SN",
	"yLJARbzYk7YsSsjMNi05WKvo2WNrI5O9ZiMYdjI8boa4zaEhNhLLVK2G2wr1t9+hDttwrLcPS56ay1jO",
	"/z4SKopPjrkraUWtaWEUhzJOmaXrOHgq6zCnc7rY7lhxoEbIuL1bcsRTNUjZbmelZPYnoAE2SbNymOkL",
	"bQ+yCt7BB/ScDGUOckhKHCmMaXGGytE/1FlqW1tttNgYqGUJ1j58eAYZ8UF3mWFiIr2VZKOnbI6oNN3Z",
	"oJ47JYOVFiuSS+3VBuX2b5hvpFFPxlBnS4fWrO5QbQM+AIEv1zLy/Inegz4j2hcBbgTR68NVMfP2yseK",
	"nKv4/IF23bo6o22K0RB0LpYK8Y8ohOQDxLSrQiqihG/URjVmdIW5BwnHkannVPhz1Vp745cSAfBIQZIt",
	"IGZ6tq3ExF/TB2BoDa834N9rNSpEHPM0MD7+U7I2H99Qx/1a1XmWVlhcWJhfIAfBMBvTmPH3X+W21Xu7",
	"0eLeYOdVwWy5bwVnZgVnGbWyUIM8rGoJVp5lC5LEQAIBWLZ9xRyEuNCUeyvKvOJcXtY+yccMVikJIKuo",
	"Ij6EIQT9ZVX52moEEmDVE8AgdXIT3Xmt1vx2CrVBntLU1TbIxp3CtdndzEnATxnm24/CS8wwvQHEgF2n",
	"2d59J//7sVjzX799cmbZBXRpDuXTEogN57GzExNjsqKtgmHnExBE+BX6ghg8K8T3GSLBM59GwqDCs+v3",
	"b5+LCTGXde7/pM/eFOOu41g8dmbOA7Akm/HF8/nzeVEqj2LsLJxXz+fPX2Wl8RuJkYti7D68cGUcz31M",
	"cbATP69B0l5wGQn43gZiPeCyRONm++vbN+9gjfytnIqhCDiwRDruWKwspi9qzBZOxotSCjlLIScUUjFj",
	"KQZnwiZhfDmfZ7U+hEPm26A4DrEvIXN/TzJ/sJyvy9VXNgWQXKlz45efMpczr7AbaPV6NZNiWTmgJn2S",
	"qFW5u13ulmJAjXNZfRJNFFyrXOvJuQAJv6HBdjCsFBeHdnW7Izi+a3H1xeRczSANzou1bmaytCqZ8g0Q",
	"LqCGoGTzN/2xI7KF6ftm9I7PNAZZkxclt97hhF/LEU8kqlH0qNYcpB01Ojcqz7r3EQZo3G2kcv9y6l2k",
	"xsjz3z2EBriPuXe+c8XBuVtnhJuf3GxzHvfbuMLxn9LOGalk7bxy6SopkB2XXWPpevVeycS6XpeQs9d1",
	"HzHeewZ4jRgf1XZX7zFPzE/FteQT5WqLbe5jXunS6X6WbXmMdL28CWiu67N8ps9pFjjLp2qUZVZnMLyk",
	"OKZvq2hXdHoGvoPn7n5DU6vudRC85RB9orn2jsP6kcy8oq3g1Hah2f/n/KxCJiHuY96cZpeFDkPIcoN1",
	"aXkjfy+QHt1S1Gcquuc8zR38ezs0+m/67HXOjaPySMZN/U2b7PUc07mQfXh9V+fajFR+PqnKn9B+sO8J",
	"q7b/5c3IkVy39q3SifmluPt52hzbt6PqcNd+LltWjUa41q3NszzZdlnUGhXHMlfNXP3E4n8BXFToRiUt",
	"pQ/RyiE326F0xSxaq4yFn32ISMWCLL3fE/O7yQdNzIZGm+BLj9Fl6DZoPFYYpt4kcOIDV5OxZx9aa6mT",
	"+7ivm9m5qNJBvMsfaPcbNzolVCt0TiOX2NE4/Ty8NjevUMM9hrF+5QZPbiF1V35O31T22MIGYhMZxWb7",
	"xonNopabl2Mfi+LzbrUqOndNrU6q1vIX7XIUCE+kX83GpBPrV5u9l6NYRc/rbsX6oRj17UA1FiNqF+S0",
	"jNgXg0/MCHUXu8s1c43S+9HtnKbU/ziORPvO8QUZPNmdo9vaySsjU5s6TdOdSzR11U/q9B2RjnQyurgT",
	"0USeWqND8nHs1yWaLSYv/Sbu/kKtNjlECd+E28pNYU0wqFGJk90aNogEVW5/qWeS93KtJhozpqS6Mn0Z",
	"ZpTRsMdt/yBGTGxAa3fzL3P/SrJr2Ff9Rc+KlqxT86OrK+zZb24K5Cba6Dq+YzHxptfJ4MvZAGtK5/ob",
	"8O87apLFYwVhiq4JI4lGX5eJibP/ve0iziOpYmZik0mt6Z8m0jupMT2yBT2nOt69criPlYYoO/eu+CD3",
	"lSyS0ZvI/Ze7C+yLOsD+xHH9GwxHLwxVf4P82y1xIzkqw2FqMXkfIj/rofIjo9Hot3xqX9eamIXtduZn",
	"wz/3sWg63HnPp9IV3EjR952MT6VARNXW/DQPLV2Vp5WWRCOzYayyVkVTpYl9W3W4/JzDC0VU3H0s+yh1",
	"anOtca2RINUaNJ2GRqu77572wUTJKbfsC9qX08h6k95s839PmXVDtjg9m9jSdRBUUapFlMbl1Mhpmdpn",
	"NY+Tm2kIydnHpxgQ+HK1736rFqhmN92RXGhdu+CJt2Zt7+BTtOq73f8DAAD//wwr2c7mjQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
